# (PART) Enterprise Risk Management {-}

# ERA 1.1 - 1.3 Introduction - Brehm, et al.

Requirements to promote ERM

Definition of ERM \@ref(def:erm-def-era1)

7 [key aspect](#key-aspect-era1) of ERM

4 [categories](#risk-cat-era1) of risk

Enterprise risk model process

1. [Diagnose](#era1-diagnose): Assess all risk and consider general environment, industry, and firm specific items

2. [Analyze](#era1-analyze) what risk are critical and consider correlations; Select measures consistent with management's view of risk and prioritize

3. [Implement](#era1-implement) ways to manage the risk: avoid, reduce frequency, mitigate severity, transfer, or retain

4. Monitor the process, update when there's new risk, new ways to control or new options to transfer/treating the risk

[Goal](#ermodel-overview-era1) of enterprise risk model

Model [quality](#model-qual-era1)

4 [key elements](#key-elements-era1) of enterprise risk model: underwriting risk, reserving risk, asset risk and dependencies

* Know the different component of u/w risk

* Different asset class modeling

* Source of dependencies

Approach to [setting capital](#setting-cap-era1) based on default avoidance or threshold lower than probability of ruin

Risk measures do not tell us how much capital to hold; They tell us for a given level of capital, what the risk to the company is

Risk model can also be used to allocate capital to BUs and investment function to calculate risk-adjusted performance

## ERA 1.1 Historical Context

**Two similar quantitative initiatives** from the past

* Dynamic Financial Analysis

    * RBC (from 1990s) was the precursor to scenario testing and Dynamic Financial Analysis (DFA) but DFA didn't pan out

    * DFA requires support from many functions and was not widely used due to lack of natural champion

* Cat Model

    * Primitive in 1980s

    * Faced external and internal pressure to use cat models after HU Andrew

    * Nowadays it would be considered mismanagement for a company not to use cat models
    
There is a spectrum of acceptance for both internal and external, and ERM is somewhere between the 2 examples above

***External Pressure*** on ERM as of 2007:

* International Association of Insurance Supervision (IAIS) began development of an approach of rating insurer based on Basel II

    See 2004 IAA document

* Canada (*Dynamic Capital Adequacy Test*) and Australia (*Internaal Model Based Method*) developed and implemented regulatory requirements regarding the construction and use of internal risk models

* UK (*Financial Service Authority*) implemented Individual Capital Adequacy Standards (*ICAS*) in 2004:

    "*A firm is required to undertake regular assessments of the amount and quality of capital which in their view is adequate for the size and nature of their business...*"

* NAIC is moving towards a new audit paradigm:

    **C**apital adequacy, **A**sset quality, **R**eserves, **R**einsurance, **M**anagement, **E**arnings and **L**iquidity (**CARRMEL**)

* 2005 S&P stated that a firm's EMR program will become a critical component in its rating methodology

***Internal Champion***

* ERM needs an **internal** champion (e.g. CRO) with:

    * **Quantitative skills**
    
    * **Operational experience**
    
    * **Political skills** (executive rank) to work across organizational silos

## ERA 1.2 Overview of Enterprise Risk Management

```{definition,erm-def-era1}
ERM is the process of *systematically* and *comprehensively*:

* **Identifying** *critical* risk

* **Quantifying** their impacts, and

* **Implementing** *integrated* strategies

* To **maximize enterprise value**
```

### Key aspects of ERM {#key-aspect-era1}

*ERM* is:

1) A **process**, not a one time analysis

2) **Enterprise wide** basis

3) Focus on **critical** or **material** risk

*Risk*:

4) Has upside and downside, it's when actual outcome $\neq$ expected

5) Must be **quantified**; **Dependencies** must be evaluated and quantified
    
*Strategies*:

6) Are developed to **avoid**, **mitigate**, or **exploit** risk factors

7) Are evaluated as a **tradeoff** of **risk and return**, to maximize firm value
    
### Risk Taxonomy {#risk-cat-era1}

**Insurance Hazard**:

* Unique to insurers that is intentionally taken on to make a profit

* *In-force* exposures:

    i. *Accumulation* (CAT)
    
    ii. *Underwriting* (non-CAT)

* *Past* exposures (reserve deterioration)
    
**Financial Risk**:

* Volatility in: interest rate, FX, equity, credit, liquidity
    
* Focus on *assets* of insurance company (Insurers tend to have high $\frac{Asset}{Equity}$ ratio)

    * Financial risk impact our liability as well
    
**Operational Risk**:

* *Execution* risks of the company (things don't turn out as planned)

* Relates to threats to company value from actions (either the action itself of its consequences departed from plan)
    
**Strategic Risk**:

* Risk about *choices*: making the right/wrong choice, or refusing to choose, or fail to recognize the need to choose

* Inherent threat to the company in choosing the wrong plan given the current and expected market conditions

```{remark}
Operational and strategic risks are less amenable to *quantitative* modeling
```
    
### Enterprise Risk Model Process

[Diagnose](#era1-diagnose) $\Rightarrow$ [Analyze](#era1-analyze) $\Rightarrow$ [Implement](#era1-implement) $\Rightarrow$ [Monitor](#era1-monitor) $\Rightarrow$ Repeat

#### Diagnose {#era1-diagnose}

High level risk assessment

* All risks are considered

* Include preliminary development of **thresholds** for risk that will be considered material of significant (e.g. [Key aspect 3](#key-aspect-era1)) from above)

Table below \@ref(tab:era1-analyze-pillar) can serve as a structured way to analyze the pillars of the risk taxonomy

Table: (\#tab:era1-analyze-pillar) Categorization of uncertainties

| General Environment | Industry | Firm Specific |
| ------------------------ | ------------------------ | ------------------------ |
| Political uncertainties (*e.g. democratic changes, war, revolution*) | Input market (*e.g. supply, quality*) | Operating (*e.g. labor, supply*) |
| Government policy (*e.g. fiscal, monetary changes, regulation*) | Product market (*e.g. demand*) | Liability (*e.g. products, employment, production*) |
| Marcoeconomic environment (*e.g. inflation, interest rates*) | Competitive uncertainties (*e.g. new entrants, rivalry*) | R&D |
| Social (*e.g. terrorism*) | | Credit |
| Natural (*e.g. cat events*) | | Behavioral |

#### Analyze {#era1-analyze}

Analyze risk identified in [step 1](#era1-diagnose) for **materiality** and **prioritize**

**Critical Risk**:

* Risk with potential to exceed the company's threshold

* They should be modeled to the extent possible

* Preferably *quantified* with a probability distribution of outcomes

**Correlations** among risk factors must be recognized (distribution integrated across the various risk silos)

**Risk metrics** are calculated with the combined distribution to establish a measure of the degree of risk 

Selected **risk measures** must be **consistent** with management's view toward risk

**Prioritize** risk factors that contribute to adverse scenarios (or risk metrics) above the critical threshold

#### Implement {#era1-implement}

Focus on **managing** risks identified and analyzed as material

5 potential actions to manage risk:

1. **Avoidance**

2. **Reduction** in chance of *occurrence*

3. **Mitigate** effect *given occurrence*

4. **Eliminate** or **transfer** of the consequences

5. **Retention** (by design or by default) some or all of the risk

Speculative risk factor may provide an opportunity to capitalize on the risk, rather than manage it away

* Perform a cost/benefit or risk/return trade-off analysis

#### Monitor {#era1-monitor}

Management need to monitor the process, compare to expectations

Need to update plans and model as company or market or competitors change (not a "project" to be completed)

* New risk to address

* New ways to control them

* New options for treating or transferring risk

## ERA 1.3 Enterprise Risk Modeling Overview {#ermodel-overview-era1}

Goal: **understand** and **quantify** the relationships among the risks to the business that arise from *asset*, *liabilities* and *underwriting*

* All are affected by *internal decisions* & *external factors*

Modeling can help with *management functions* and *strategic decisions*:

* Determining capital need (to support risk, maintain rating, etc)

* Identifying sources of significant risk and cost of capital to support them

* Setting reinsurance strategies

* Planning growth

* Managing asset mix

* Valuing companies for M&A

### Quality of Models {#model-qual-era1}

**Good Model**:

* Show the *balance* between risk and reward for a *range* of different strategies

    (e.g. changing asset mix or reinsurance program or LoB to grow)

* Recognizes and reflects its own imperfection

    (Model only approximates reality and the parameters are uncertain)

**Weak Model**:

* *Over(under)state* risks $\leadsto$ Overly cautious (aggressive) choices

Things that affect the suitability and usefulness of the model

* Data quality

* Choices on assumptions and mathematical method

* Variety of different risk elements and how they are represented

**Key elements** that differentiate model quality:

* Model:

    i. Reflects **relative importance** of various risks to business decisions

    ii. Includes mathematical techniques to reflect **dependencies**
    

* Modelers:

    i. Have a **deep knowledge** of the **fundamentals** of those risks

    ii. Have a **trusted relationship** with senior management

Model should take into account the **uncertainty from other models** (*e.g. CAT, ESG, credit risk*) that are used as inputs

Risks less amenable to detailed representation in enterprise risk model (**Non-quantifiable risk**):

* e.g. Op risk (*IT exposures, pension inadequacy, key man risk, rogue traers, frade*)

* They are extremely important to the success of a business

* Requires specialized management process and difficult to incorporate into an overall risk model

* Can be modeled in bulk using informed judgments (but with high degree of uncertainty)

* Use model to manage the risk for which the modeling process is effective

* While some risks are at best weakly represented in such a model and requires other management methods

### Key Elements of ERM {#key-elements-era1}

1. Underwriting Risk

2. Reserving Risk

3. Asset Risk

4. Dependencies (Correlation)

#### Underwriting Risk {#era1-uw-risk}

***Loss Frequency and Severity Distribution***

Use statistical methods to:

* Estimate parameters

* Test quality of fit

* Understand uncertainties that remain

Common distributions for insurance loss are available in many papers

* [Transformed Beta and Gamma Distributions and Aggregate Losses - Venter](https://www.casact.org/pubs/proceed/proceed83/83156.pdf)

* Continuous Distributions - Kreps

***Pricing Risk***

Instability from variations in the premiums as well as losses

* Misestimation of projected losses as well as competitive market pressures

* Deficiency may exist for many years for long tailed lines $\Rightarrow$ Accumulation of reserve deficiency

* Model should include u/w cycle as it contributes significantly to pricing risk

    * See additional details in [ERA 5.2](#era5-uw-cycle-intro)

***Parameter Risk***:  
Misestimated parameters, imperfect form and risk not modeled (Likely largest risk net of reinsurance (larger than cat exposure))

* **Estimation Risk**:  
Error in estimations the form and parameters
    
    * Depends on available data (i.e. more and better data *reduces* this risk)

* **Projection Risk**:  
Error on forecast of future value even if we fit the historical data accurately
    
    * Examples:
    
        * Freq/Sev trend from the time of the data to the current and future underwriting periods
    
        * Development of ultimate losses
    
    * Affected by macro factors (e.g. inflation) and the corresponding dependencies should be reflected in the model

    * Unexpected change in external risk conditions also add to projection risk, e.g.
    
        * Lower fuel price $\Rightarrow$ Increased driving
        
        * Long term shift to more extreme weather

* **Event Risk**:  
Causal link between a large unpredictable event and losses to an insurer

    Example:
    
    * Court ruling that favors a large group of policyholders (e.g. class action)
    
    * Exposure that existed, unknown, for many years comes to light (e.g. asbestos)

    * New cause of loss emerges that was previously regarded as not covered (e.g. environmental, CD)

    * Regulator or court expands coverage by barring important exclusions

    * New entrant into market reduces rates to grab market share

* **Systematic Risk**:

    * Operates simultaneously on a large number of policies
    
    * Undiversifiable, i.e. do not improve with added volume

    * e.g. macro factors such as inflation
    
* See additional detail in [ERA 3.2](#era-3.2-intro)

***Catastrophe Modeling Uncertainty***  
Exposure to natural and man-made cat

* Likely largest risk after parameter risk, special case of parameter risk

* Based on proprietary cat models, further source of uncertainty

    * Differences between commercial models and different versions of the same model
    
    * Considerable amount of uncertainty in the probabilities of various events and the amount of insured damage

    * Additional uncertainty from data quality
    
        * Mismatches of company data fields and cat model assumptions

* Can quantified by the use of more than one model for each peril

* Cat distributions are subject to the same considerations of parameter risk and correlation as other risk distributions

#### Reserving Risk

Adverse development can be significant for long tailed lines

$\uparrow$ reserve uncertainty $\Rightarrow$ $\uparrow$ capital requirement & $\uparrow$ time holding the capital

Model needs to capture both process variance and parameter risk

Key aspects of risk modeling process

* Specifying the reserve runoff model

* Testing it with quality of fit measures

Unearned premium reserve should be modeled in [underwriting risk](#era1-uw-risk)

#### Asset Risk

Need to focus on issues of the specific markets that the company operates

Main asset classes: **equities**, **fixed income**, **real estate**

* Different types of fixed income are important in different regions

* FX and inflation are closely related to asset modeling as well

***Asset Modeling: Probabilistic Reality***

* Modeling scenarios consistent with historical patterns

* Generate a large variety of scenarios against which to test the insurer's strategy

* Scenarios are weighted by probability

* Scenarios should be reasonable when compared to historical patterns

***Asset liability matching***

* Offset between insurance risk and investment risk

* P&C companies can opt for longer duration assets and not match the liabilities to increase investment return while still maintain reasonable ALM risk

    * Need to consider that P&C liabilities are inflation sensitive as well
    
    * Or if liabilities are carried at PV marked to current interest rate

Efficient Frontier: $\sigma$ vs $\operatorname{E}[Return]$

* See how it changes by modifying reinsurance structure or asset mix

* More details in [ERA 2.4](#era2.4-intro)

***Modeling Considerations***

* **Bonds**:

    * Model with arbitrage free models  

    * Should capture historical features of bond markets
    
        (high auto-correlations and distribution of yield spreads)

* **Equities**:

    * Incorporate correlations with bonds
    
    * Geometric Brownian motion model with additional volatility is more realistic
    
        (Allow for more extreme motion or even discontinuities)

* **FX**:

    * First model interest rates of the currencies then model the FX rates
    
    * Changes in actual and anticipated interest rates in two countries lead to changes in the FX rates
    
    * Interest rate movements across different economies are correlated as well

#### Dependencies

Important to capture dependencies or else the model will be unrealistically stable

***Sources of Dependencies***:

* Simultaneous impact of macro economic conditions on many risks

    A good ESG should capture the dependence between inflation, interest rates, equity values, etc
    
    * This will impact asset values
    
    * Inflation will impact underwriting losses, loss reserve development
    
    * Interest rates may influence the underwriting cycle

* U/w cycle, loss trends and reserve development can be correlated across LoB and with each other

* Cat and other event losses can cross lines

* Large man made cat (e.g. 9/11) can have impact on both insurance and market risk

* Difficult to quantify

    * May reference studies of multiple insurers, public insurance industry information and macroeconomic data
    
    * Still require professional judgement

***Modeling Dependencies***:

* Avoid using just the correlation coefficient to describe and oversimplify dependency

* We are most interested in the tail dependency

    * e.g. High inflation or large cat that impacts multiple LoB that would typically be uncorrelated

* Use copulas to capture different forms of dependency

    * See [ERA 3.3](#era3.3-intro) for more details

### Setting Capital Requirements {#setting-cap-era1}

ERM help insurer fin the optimum level of capital that balances efficiency and prudence

* Policyholders (acting through regulators and rating agencies) demand adequate capital

* Shareholders require that capital be used efficiently

Set capital to maximize insurer's value creates a conceptual framework that unifies the competing requirements of prudence and efficiency

* See [ERA 2.2](#era2.2-intro) for more detail

Approaches to setting capital requirements:

**1. Default Avoidance**:  
Focused on the **tail** and protecting **policyholders**

Caveat:

* S/h will be hurt at much lower loss amount

* We have the least confidence in the tail of the model

$\hookrightarrow$ More feasible and relevant to focus on thresholds less extreme than default

**2. Other Thresholds** (Lower than probability of ruin):

i. Probability of downgrade

    * Significant loss $\leadsto$ $\downarrow$ financial rating $\leadsto$ $\downarrow$ franchise value > loss itself
    
    * Franchise value: customer base, agency relationships, reputation, infrastructure and expertise

ii. Sufficient capital to service renewals

iii. Survive and thrive after major cat

#### Convert Probability to Loss

Associate the selected probability level with amount of financial loss

* Smallest amount of loss, $\alpha \%$ of the time $\Rightarrow$ $VaR_{100 - \alpha \%}$

* Average loss, $\alpha \%$ of the time $\Rightarrow$ $TVaR_{100 - \alpha \%}$

* 1-in-$x$ years event loss no more than $y \%$ of capital $\Rightarrow$ $\dfrac{100}{y} \times TVaR_{1 - \frac{1}{x}}$

**Important**: Risk measures do not tell us how much capital to hold; They tell us for a given level of capital, what the risk to the company is

* Determination of optimal capital level is not purely a risk measurement exercise

    * Need to balance sufficient financial strength to attract business and the need of shareholders to achieve attractive return

* Risk measurement quantifies the risk the company is exposed to in relationship to the capital so established

* Strategic risk decisions can then be made in the framework created

* Capital is not set by risk measures, but analyzed by them to understand the sources of risk and for further strategic decision making

#### Risk Adjusted Performance

Allocate capital to business units $\Rightarrow$ Calculate the rate of return $\dfrac{\text{Profit}}{\text{Capital}}$ for that unit $\Rightarrow$ Compare RoR across BUs

Can also allocate risk capital to investments $\Rightarrow$ Compare riskiness of investments and u/w

* Validity of such a comparison will depend on the consistency of the risk measures that are developed

* See [ERA 2.2](#era2.2-intro) for more detail