# ERA 2.2 Risk Measures and Capital Allocation - G. Venter

Know the risk measures

* Moment based

* Tail based ($VaR$, $TVaR$, $XTVaR$, $EPD$)

* Probability transform

* Generalized moments

Capital a company should hold depends on *practical considerations*, not simply derived from a risk measure

Allocation of risk measures

* [Proportional](#proportional-era2-2)

* [Co-measures](#co-measures-era2-2)

Allocation is marginal (\@ref(def:marginal-era2-2)) if the change to the company’s risk measure from a small change in a single BU is attributed to that business unit

* Scalable risk measures (\@ref(def:scalable-era2-2)) 

* Suitable alloaction (\@ref(def:marginal-era2-2))

* A risk measure can have many co-measures but [only 1](#marginal-impact-era-2-2) will be marginal

Can bypass the above if we can just allocate the cost of capital

## Introduction {#era2-2-intro}

VaR by itself it too simplistic for insurance companies

*Advantages* attributed to **Economic Capital**

* **Unifying** measure for *all risks* in an organization

* More meaningful *to management* than RBC or Capital Adequacy Ratios (e.g. Prem/Surplus, Res/Surplus)

* Forces firm to **quantify** risks it faces and **combine** them into a probability dist^n^

* Provides a **framework for setting acceptable risk levels** for the company and its business units

```{remark}


* Many other risk measures have the advantages above (not just "economic capital" under VaR)

* Insurers typically use multiple risk measure to see if a consistent picture emerges

* VaR is typically calculated from the distribution of all risks and then allocate down to inidividual units

    This provides consistent measurement of risk across units
```

***Target Probability Level***

* Current modeling approaches are not able to accurately estimate losses deep in the tail like 1-in-3000 (99.97%) event

* Bond ratings are discusses at this level but the ratings are not tied to the probabilities

    * Ratings are defined by factors (e.g. interest coverage)

    * Probabilities are published retrospectively after observing rated bonds for many organizations for many years
    
* Target probability level is *artificial* (no theoretical support)

    * Sometimes it is just backed out based on the modeled distribution
    
* **Suggestion**: Should just express actual capital under various risk measures

* The company sometimes compare held capital to the loss dist^n^ stating that it's holding capital to cover a 1-in-x year event. But not the other way around like setting the capital based on it

* Modeling difficulty of the tail can be circumvented by focusing on events that can lead to impairment of the company, not just insolvency

## Risk Measures

3 major class of risk measures

1. [Moment-based](#moment-base-era2-2) (*e.g. mean, variance*)

2. [Tail-based](#tail-base-era2-2) (*e.g. VaR, TVaR*)

3. [Probability Transformation](#prop-trans-era2-2) (*e.g. WTVaR, Mean of Transformed dist^n^*)



```{definition, loss-risk-measure-era2-2}
Loss here is not just loss from claims, but "negative profit" after considering income (e.g. premium), expenses etc

* $Y =$ Losses

* $\rho(Y) =$ Risk Measure
```

### Moment-Based Measures {#moment-base-era2-2}

$\mathrm{E} \left[ Y^k \right]$ is the k^th^ moment of $Y$ which represent losses

* 1^st^ moment = Mean

* 2^nd^ central moment = Variance = $\mathrm{E}\left[ (Y-\mathrm{E}[Y])^2 \right]$

    * S.d. is preferred as it has the same units as the loss
    
    * Semi-s.d. only captures unfavorable deviations
    
    * Quadratic risk measures are not enough to capture market attitudes to risk (they do not capture skewness)

* 3^rd^ moment = Skewness

**Exponential Moments**

$$\mathrm{E}\left[Y e^{cY/\mathrm{E}[Y]}\right]$$

* Captures all the moment using taylor expansion

* Scaled to \$ but captures the effect of large losses on the risk exponentially

* Does not exist unless there is a maximum possible loss

### Tail-Based Measures at $\alpha$ Percentile {#tail-base-era2-2}

Table: (\#tab:era2-2-tail-measure-tab) Tail-Based Measures

| Risk Measure | Name                | Description            |
|:------------ |:--------------------- |:-------------------------------------- |
| $VaR$        | Value at Risk       | $\alpha$^th^ Percentile                |
| $TVaR$       | Tail Value at Risk  | Avg loss above $\alpha$^th^ percentile |
| $XTVaR$^1^ | XS Tail Value at Risk | $TVaR - Mean$                        |
| $EPD$^2^        | Expected Policyholder Deficit | $(TVaR - VaR) \cdot (1 - \alpha)$ |
| Value of Default Put Option^3^ |      | Market cost of insuring for losses over $VaR_{\alpha}$|

1. $XTVaR$ focuses on funding losses above the mean

2. $EPD$ = unconditional expected value of defaulted losses if capital = $VaR_{\alpha}$

    * If there was no risk premium required, this is the cost of insuring for losses over $VaR_{\alpha}$
    
    * First part of the equation is the expected loss given default and the second part is to get to the unconditional value
    
    * Expected loss of insuring the company for losses excess of their capital amount (here it's $VaR_{\alpha}$)

3. Value of default put is great than EPD, it includes an additional risk premium (market cost of insuring for losses over $VaR_{\alpha}$)

    * Value of insuring against default
    
    * Estimate using option pricing

### Probability Transforms {#prop-trans-era2-2}

To recognize that large losses are worse for the firm in more than a linear way (e.g. losses twice as big is > twice as worst)

Change the loss distribution function by putting more weight (add probability) to the worst losses

* e.g. Esscher transform $f^*(y) = k \cdot e ^{y/c} \: f(y)$

    * Lower $c$ $\Rightarrow$ Higher losses from the transformed dist^n^

    * Can get non sensical results for $c$ that's too low

* $EPD$ on a transformed dist^n^ can give us the value of the default put

    * The largest losses will have additional weight (to account for the risk premium we discussed above)

```{remark}


* Most asset pricing formulas like CAPM and Black-Scholes can be expressed as transformed means  
$\therefore$ transformed means are a promising risk measure for determining the market value of risk

* Complete market is where any risk can be sold, but we work in incomplete markets

* Theory of pricing in incomplete markets favors:

    * Minimum Martingale Transform (MMT)
    
    * Minimum Entropy Martingale Transform (MET)
    
    * These give reasonable approximations of reinsurance prices
    
* Mean under then Wang transform closely approximates market prices for bonds and CAT bonds

* We can calculate other risk measures (e.g. VaR) on the transformed distribution

    * $WTVaR$ (Weighted TVaR) is $TVaR$ on a transformed distribution
    
    * EPD on transformed distribution can use to estimate value of default put
```

### Generalized Moments

Includes more than just $\mathrm{E}[Y^k]$, can include all of the above risk measures (Not just expectations of powers of the variable)

**TVaR expressed in generalized moments**

$$TVaR_{\alpha} = \mathrm{E} \left[ Y \cdot \left( Y > F^{ -1}_Y(\alpha) \right) \big| Y > F^{ -1}_Y(\alpha) \right]$$

* $(Y > b) = \begin{cases} 1 & : Y > b\\ 0 & : \text{otherwise} \end{cases}$

* Average of $Y$ when $Y$ > than the $\alpha^{th}$ percentile: $F^{ -1}(\alpha)$

**Spectral Measures**

* This includes many tail measures that can be written in the following form

$$\rho(Y) = \mathrm{E} \left[ Y \cdot \eta \left( F(Y) \right) \right]$$

* $\eta \geq 0$

* Multiply the loss by a non-negative scalar $\eta(Y)$ when taking the expectations

* TVaR is a spectral measures

**Blurred VaR**

* Takes the distance from the target percentile as the weighting function

$$\eta(p) = \mathrm{exp} \left \{ - \theta (p-\alpha)^2 \right \}$$

* Give more weight to losses near $\alpha^{th}$ percentile while still using the whole distribution

* $\theta$ controls how quickly the weight drops of as we get further from $\alpha$

***

Which risk measures to use

* $TVaR$ at a **low percentile** is preferred as it captures all risks above this level  

    Set at level where we begin to loss capital

    * High percentile is not recommended as it ignores all risk below that percentile

* Try to get close to **market value** of risk

    * $WTVaR$ with the MET is promising, or
    
    * Exponential moment $\mathrm{E}[Y e^{cY/\mathrm{E}[Y]}]$

## Required Capital

Capital a company should hold depends on **practical considerations**, not simply derived from a risk measure

* Risk measures should be used to measure the safety of the capital

***Considerations*** that drive capital requirements:

* **Customers reactions**:  
Well capitalized insurer $\Leftarrow$ vs $\Rightarrow$ better price  
Know your customer base, whether they are price or capital sensitive

    * $\downarrow$ rating $\Rightarrow$ $\downdownarrows$ of cumtomers since customers that want a higher level can quickly leave

    * $\uparrow$ rating $\Rightarrow$ $\upharpoonleft$ of growth since higher rating just provides an opportunity to compete with other insurers that already have the business

* **Keeping renewal business**:  
Have enough capital so that in adverse scenario there is still enough capital to service renewals that is x% of the business

    * Since renewal business are more profitable

Once capital level has been established, compare it against different risk measures

* Look at % of capital lost a various probability levels

* $TVaR$ is a better risk measure than $VaR$ for a given percentile since $VaR$ is just the smallest loss XS of a percentile, $TVaR$ is the average

## Capital Allocation

Allocate the total risk measure to each BUs for the following **purposes**:

1. Measure the amount of risk each BU **contributes**

2. Set **capacity** and *policy limits* for each BU

3. Calculate **risk-adjusted profitability**    

    * RORAC: $\dfrac{\text{Profit}}{\text{Allocated Capital}}$
    
    * EVA = Profit - Cost of Capital

```{definition}


$Y$: Losses of a company with CDF $F(y)$

$X_j$: Losses for each BU, $\sum_j X_j = Y$

$\rho(Y)$: Risk measure of $Y$, $\mapsto$ a real number

* $\rho(Y) = \sum_j r(X_j)$

$r(X_j)$: Allocation of risk measure to the individual BUs

* Usually different from $\rho(X_j)$, which is the risk measure applied to BU $j$
```

### Proportional Method {#proportional-era2-2}

Allocate risk measure in proportion to the risk measure applied to each unit

\begin{equation}
  r(X_j) = \dfrac{\rho(X_j)}{\sum_i \rho(X_i)} \rho(Y)
  (\#eq:prop-method-allocation-era2-2)
\end{equation}

* This works for any risk measure

### Co-Measures {#co-measures-era2-2}

\begin{equation}
  r(X_j) = \mathrm{E}[h(X_j) \cdot L(Y) \mid g(Y)]
  (\#eq:co-measures-method-era2-2)
\end{equation}

Given that:

* $\rho(Y)$ is expressed as a conditional expected value

$$\rho(Y) = \mathrm{E}[h(Y) \cdot L(Y) \mid g(Y)]$$

* $h(\cdot)$ is additive

$$h(u+v) = h(u) + h(v)$$

$\hookrightarrow$ $\rho(Y) = \sum_j r(X_j)$

* This is a marginal allocation that sums to the total risk measure

Table: (\#tab:era2-2-co-measure-tab) Co-Measures

| Risk Measure | $h(Y)$ | $L(Y)$ | Condition | Co-Measure |
|:------------------ |:------ |:------ |:--------- |:--------------- |
| $TVaR$ | $Y$ | $1$ | $F(Y) > \alpha$ | $\mathrm{E}[X_j \mid F(Y) > \alpha]$ |
| $VaR$ | $Y$ | $1$ | $F(Y) = \alpha$ | $\mathrm{E}[X_j \mid F(Y) = \alpha]$ |
| Standard Deviation^1^ | $Y - \mathrm{E}[Y]$ | $\dfrac{Y - \mathrm{E}[Y]}{\sigma_Y}$ | none | $\dfrac{\mathrm{Cov}(X_j,Y)}{\sigma_Y}$ |
| $XTVaR$^2^ |   |   |   | $\mathrm{E}[X_j \mid Y > b] - \mathrm{E}[X_j]$

1. Note for s.d.:

$$\rho(X_j) = \dfrac{\mathrm{Cov}(X_j,Y)}{\sigma_Y} = \mathrm{E} \left [ (X_j - \mathrm{E}[X_j]) \cdot \dfrac{Y - \mathrm{E}[Y]}{\sigma_Y} \right ]$$ 

2. For $XTVaR$:

$$\rho(Y) = \mathrm{E}[Y - \mathrm{E}[Y ]\mid Y > b]$$
    
  * Note the condition is on loss amount $Y$ not the percentile
    
  * Expected losses in unit $j$ when the company has a loss above $b$ less the expected losses in unit $j$

```{remark}
Under $TVaR$ and $XTVaR$

* At low threshold, unit with higher mean have higher allocation

* At higher threshold, unit with higher variance have higher allocation
```

#### Co-$TVaR$ and -$VaR$

$TVaR$:

$$r(X_j) = \mathrm{E}[X_j \mid F(Y) > \alpha]$$
    
* Average losses in unit $j$, condition on when the **firm** (Just like in co-measures) has losses XS the $\alpha^{th}$ percentile

$VaR$:

$$r(X_j) = \mathrm{E}[X_j \mid F(Y) = \alpha]$$
    
* Expected value of losses in unit $j$, condition on when the **firm** has losses at the $\alpha^{th}$ percentile

* *Caveat*: Difficult to calculate because it is estimating a single point in the dist^n^, results from sims can be quite variable

* Typical you're conditioning on the BU's $\alpha^{th}$ percentile

**Not marginal** if the condition is not on the firm's $\alpha$

* Marginal allocation means as unit grows, it is charged with the additional capital it requires

* Not marginal means the individuals don't sum to the total (?)

### Having a Marginal Method

```{definition, marginal-era2-2}
**Marginal Allocation**:  
Allocation is marginal if the change to the company's risk measure from a small change in a single BU is attributed to that business unit

* Consistent with concept that price should be proportional to marginal cost

* Leads to suitable allocation (\@ref(def:suitable-era2-2))
```

```{definition, scalable-era2-2}
**Scalable Risk Measures**:  
A small proportional change in the business (e.g. 5%) change the risk measure by the same proportion (e.g. 5%)

* This is Homogenous of degree 1:

    $\rho(aY) = a \cdot \rho(Y)$

* Most measures in currency units have this property (e.g. S.D., TVaR) but not variance (currency^2^) and probability of default (unitless)

* Scalable risk measures are both *marginal* and *additive*
```

```{remark}
For many companies and BUs, growth in exposure units can approximate homogeneous growth

* Proportional change can be achieve from proportional reinsurance and normal growth

    * Except for companies that write large policies compared to their volume; Transformed risk measure might still work
```

```{definition, suitable-era2-2}
**Suitable Allocation**:  
Growing a unit that have above average profit/risk will increase the profit/risk for the company

Given:

$$\dfrac{P_j}{r(X_j)} > \dfrac{P}{\rho(Y)}$$

We can show:

$$\dfrac{P + \epsilon P_j}{\rho(Y + \epsilon X_j)} > \dfrac{P}{\rho(Y)}$$

Where: $P_j$ is the profit for the $j$^th^ business unit and $P$ is the profit of the company

* This is based on pluggin in the definition of $r(X_j)$ below
```

### Marginal Impact {#marginal-impact-era-2-2}

A risk measure can have many co-measures but only 1 (the following form) will be marginal

$$r(X_j) = \lim \limits_{\epsilon \rightarrow 0} \dfrac{\rho(Y + \epsilon X_j) - \rho(Y)}{\epsilon} = \dfrac{\partial \rho(Y)}{\partial X_j}$$

* This is the derivative of the firm risk measure w.r.t. growth in BU $j$

* Even under non-homogeneous growth, the risk measure is still a decomposition (sum to the total) and is often *close to marginal*

***

$XTVaR$

$$\dfrac{\partial\rho(Y)}{\partial X_j} = r(X_j) = \mathrm{E}[X_j \mid F(Y) > \alpha] - \mathrm{E}[X_j]$$

* Scalable when done XS of a percentile $\alpha$ (not when done XS a constant $b$)

***

Variance

$$\rho(Y) = Var(Y)$$

$$r(X_j) = \mathrm{Cov}(X_j,Y)$$

* Not scalable (since $Var(aY) = a^2 Var(Y)$), so not marginal?

***

$VaR$

$$\rho(Y) = VaR_{\alpha}(Y) = \mathrm{E}[Y \mid F(Y) = \alpha]$$

$$r(X_j) = \mathrm{E}[X_j \mid F(Y) = \alpha]$$

***

Standard Deviation

* Spreading the s.d. $\propto$ mean is **not marginal**:

$$\rho(Y) = Stdev(Y) = \mathrm{E}\left[ \dfrac{Y \cdot Stdev(Y)}{\mathrm{E}[Y]} \right]$$

$$r(X_j) = \mathrm{E}\left[ \dfrac{X_j \cdot Stdev(Y)}{\mathrm{E}[Y]} \right] = \dfrac{\mathrm{E}[X_j]}{\mathrm{E}[Y]} \cdot Stdev(Y)$$

* **This is marginal**: $h(Y) = Y - \mathrm{E}[Y]$ and $L(Y) = \dfrac{(Y - \mathrm{E}[Y])}{Stdev(Y)}$

$$\rho(Y) = \mathrm{E}\left[ \dfrac{Y - \mathrm{E}[Y]^2}{Stdev(Y)} \right] = Stdev(Y)$$

$$r(X_j) = \mathrm{E}\left[ \dfrac{(X - \mathrm{E}[X])(Y - \mathrm{E}[Y])}{Stdev(Y)} \right] = \dfrac{\mathrm{Cov}(X_j,Y)}{Stdev(Y)}$$

***

Exponential Moment

$$\rho(Y) = \mathrm{E}[Y \cdot e^{cY/\mathrm{E}[Y]}]$$

$$r(X_j) = r_1(X_j) + \dfrac{\mathrm{E}[X_j]}{\mathrm{E}[Y]} \cdot c \cdot \mathrm{E} \left [ Y \cdot e^{cY/\mathrm{E}[Y]} \cdot \left \{ \dfrac{X_j}{\mathrm{E}[X_j]} - \dfrac{Y}{\mathrm{E}[Y]} \right \} \right ]$$

* Without the curly bracket it is just allocating $c \cdot \rho(Y)$ $\propto$ the mean $\dfrac{\mathrm{E}[X_j]}{\mathrm{E}[Y]}$

* Curly bracket (XS ratio factor) adjust for correlation, where BU that have large $X_j$ when Y is also large will have additional allocation

* BUs that don't contribute to large losses will be negative in the curly bracket, receive reduced allocation

***

EPD

$$EPD_{\alpha} = (TVaR_{\alpha} - VaR_{\alpha}) \cdot (1 - \alpha)$$

$$\rho(Y) = \mathrm{E}[Y - B \mid F(Y) > \alpha] \cdot (1 - \alpha)$$

where $B = VaR_{\alpha}(Y) = F_Y^{-1}(\alpha)$

$$r(X_j) = (CoTVaR - CoVaR) \cdot (1-\alpha)$$

* Only scalable when XS of a percentile

***

$RTVaR = TVaR + c \cdot Stdev(Y \mid F(Y) > \alpha)$

* $h_1(Y) = Y$

* $h_2(Y) = Y - \mathrm{E}[Y|F(Y) > \alpha]$

* $L_1(Y) = 1$

* $L_2(Y) = \dfrac{c[Y - \mathrm{E}[Y \mid F(Y) > \alpha]]}{Stdev(Y \mid F(Y) > \alpha)}$

Condition:

$F(Y) > \alpha$ for both

$r(X_j) = \mathrm{E}[X_j \mid F(Y) > \alpha] + c \dfrac{Cov(X_j, Y \mid F(Y) > \alpha)}{Stdev(Y \mid F(Y) > \alpha)}$

***

Table: (\#tab:era2-2-co-measure-tab) Co-Measures

| Risk Measure | $h(Y)$ | $L(Y)$ | Condition | Co-Measure |
|:--------------- |:------ |:------ |:--------- |:------------------ |
| $TVaR$ | $Y$ | $1$ | $F(Y) > \alpha$ | $\mathrm{E}[X_j \mid F(Y) > \alpha]$ |
| $VaR$ | $Y$ | $1$ | $F(Y) = \alpha$ | $\mathrm{E}[X_j \mid F(Y) = \alpha]$ |
| Standard Deviation | $Y - \mathrm{E}[Y]$ | $\dfrac{Y - \mathrm{E}[Y]}{\sigma_Y}$ | none | $\dfrac{\mathrm{Cov}(X_j,Y)}{\sigma_Y}$ |
| $EPD$ | $X - \mathrm{E}[X \mid F(Y) = \alpha]$ | $1-\alpha$ | $F(Y) > \alpha$ | See 1. |

1. $(CoTVaR - CoVaR) \cdot (1-\alpha)$

### Using Decomposition

If the allocated risk measure $r(X_j)$ is a decomposition of the company risk measure $\rho(Y)$ then we can use the measure to measure **risk-adjusted profitability** of a BU

$$\dfrac{P_j}{r(X_j)}$$

If the risk measure $\propto$ the market value of risk $\Rightarrow$ the BU with higher ratio have more profit relative to the value of risk they are taking

* But since don't know how to determine the market value of risk (i.e. don't know which risk measure is $\propto$ the value of risk) $\Rightarrow$ Use several risk measures and hope one is close and that the indicated *strategic directions* are consistent with each other

* Question on how to determine the market value of risk have not been settle yet, likely a risk measure on a transformed probability but we don't know yet

## Allocating the Cost of Capital

Compare profitability among the BU by allocating **cost of capital** for each BU

2 possible definitions for cost of capital $C_j$

1. Option pricing: Value of the right to call upon the capital of the firm

    * Added value = $P_j - C_j$ 
    
    * *Caveat*: Difficult to value as the timing is not fixed in advanced
    
2. Market value of a stop loss that attach at *zero profits* for the BU

    1. Start with expected value of the stop-loss
    
    2. Use probability transform and theory of pricing in incomplete markets (e.g. MET)
    
    * Practical estimate: Mean + 30% of s.d. would apply a consistent risk load to the BU
    
## Summary

Allocating capital, even using marginal decomposition is arbitrary and artificial

* **Arbitrary** because different risk measures give us different allocations and therefore different answers

* **Artificial** because the business unit has access to the entire capital of the firm, not just a portion of it

Using a value added approach, by allocating *cost of capital* is more economically realistic