# ERA 2.5 Measuring Value in Reinsurance - Venter, Gluck, Brehm

Value of reinsurance

1) Provides [stability](#era-2-5-sec-1)

    * [Based on reinsurance premium and expected recoveries](#era-2-5-stability-1)
    
        * Metrics \@ref(def:era-2-5-metrics-1) and \@ref(def:era-2-5-metrics-2)

    * [Amount of protection](#era-2-5-stability-2)
    
        * Metrics \@ref(def:era-2-5-metrics-3)

    * [Net Premium - Net loss](#era-2-5-stability-3)
    
        * Metrics \@ref(def:era-2-5-metrics-4), \@ref(def:era-2-5-metrics-5), \@ref(def:era-2-5-metrics-6) and \@ref(def:era-2-5-metrics-7)

    * [Distributions](#era-2-5-stability-4)
    
        * Density and CDF
        
        * Space needle diagram
        
        * Cost benefit diagram
        
        * Combined ratio is bad

    * $\star$ [Efficient frontier](#era-2-5-stability-5)

2) Frees up [capital](#era-2-5-sec-2)

    * $\star$ Cost of capital reduction metrics \@ref(def:coc-reduct-met-1) and \@ref(def:coc-reduct-met-2)
    
    * $\star$ Capital can be based on [theoretical](#theo-model-era-2-5) or [practical](#prac-model-era-2-5) model
    
    * [Accumulation risk](#era-2-5-acc-risk): as-if reserve \@ref(def:as-if-res-era-2-5)
    
    * [Capital consumed](#era-2-5-cap-consum) and the equation \@ref(eq:cap-con-equa)

3) Adds to the [value](#era-2-5-sec-3) of the firm

    * Difficult to do but some recent study results

## Introduction {#era2-5-intro}

Value of reinsurance

1) [Provides stability](#era-2-5-sec-1)

2) [Frees up capital](#era-2-5-sec-2)

3) [Adds to the value of the firm](#era-2-5-sec-3)

Naive calculation: Sum(cash flow over contract length)

* (-) Premium and reinstatement

* (+) Ceding comm and reinsurance loss

$\hookrightarrow$ Will always show reinsurance is a bad deal especially after discounting the cashflow

* Make sense since reinsurers need to make a profit

* Cases where it's "profitable" to the cedant, it'll either be repriced or the cedants results are really poor

## Quantifying Stability and Its Value {#era-2-5-sec-1}

Measuring the value of reinsurance is more than calculating the expected cashflow from the reinsurance program

Significant judgement is required to evaluate the cost-benefit tradeoff

Metrics to measure and value **stability**:

* Ratio and difference of $\text{Reinsurance Premium}$ and  $\mathrm{E}[\text{Recovery}]$

* Expected loss under different programs

* $\text{Premium} - \mathrm{E}[\text{Loss}]$ under different programs

    * $\sigma$, percentiles, whole distribution
    
    * Space needle view,
    
* Distribution of other metrics

    * cost benefit diagram, pre tax net income, combined ratio
    
* Efficient frontier charts

### Reinsurance Premium and Expected Recoveries {#era-2-5-stability-1}

```{definition, era-2-5-metrics-1, name ="Metrics 1"}
$$\dfrac{\mathrm{E}[\text{Recovery}]}{\text{Reinsurance Premium}}$$
```

```{definition, era-2-5-metrics-2, name ="Metrics 2"}
Net Cost of Reinsurance
$$\text{Reinsurance Premium} - \mathrm{E}[\text{Recovery}]$$
```

```{remark}


* On a PV basis?

* $\mathrm{E}[Recovery]$ is net of reinstatement premiums, typically based on simulation results

* Should gauge how significant the net cost of reinsurance is by comparing to the firm's expected earnings for the year
```

### Amount of Protection {#era-2-5-stability-2}

```{definition, era-2-5-metrics-3, name ="Metrics 3"}
Compare $\mathrm{E}[\text{Net Loss}]$ $\forall$ programs

$$\mathrm{E}[\text{Net Loss}] = \mathrm{E}[\text{Gross Loss}] - \mathrm{E}[\text{Recovery}]$$
```

### Premium Less Expected Loss {#era-2-5-stability-3}

Going forward we are considering *Net* $\text{Premium}$ - *Net* $\mathrm{E}[\text{Loss}]$

* Only consider premium and losses

* Does not include expenses or investment income

```{definition, era-2-5-metrics-4, name ="Metrics 4"}
$$\text{Premium} - \mathrm{E}[\text{Loss}]$$

* Compare $\forall$ programs
```

```{definition, era-2-5-metrics-5, name ="Metrics 5"}
$$\sigma_{\text{Premium} - \mathrm{E}[\text{Loss}]}$$

* ***Caveat***: Can be lowered by removing favorable outcomes
```

```{definition, era-2-5-metrics-6, name ="Metrics 6"}
1^st^ percentile (most favorable) $\text{Premium} - \mathrm{E}[\text{Loss}]$
```

```{definition, era-2-5-metrics-7, name ="Metrics 7"}
Worst simulated outcome $\text{Premium} - \mathrm{E}[\text{Loss}]$

* Might be too extreme to look at 1-in-25K (99.996%)
```

```{remark}


* Here we are sticking to high percentile means bad, similar to how we used to look at loss, but can flip it for looking at earnings
```

### Distribution Based {#era-2-5-stability-4}

**Density** of $\text{Premium} - \mathrm{E}[\text{Loss}]$

* Compare shapes for different programs

* See if it's giving up the upside and like how does the tail look

**CDF** of $\text{Premium} - \mathrm{E}[\text{Loss}]$

* Pick a percentile and read it across the graph to find the value at that percentile for each curve

* Look at the difference between different programs at *each percentile*

*Note on difference of distribution*:

* Event that generate a given percentile is different across programs

    * Reinsurance changes the order of the outcomes
    
* We are interested in the *difference of the distributions*

    * NOT interested in the distribution of differences (as it doesn't make sense? due to the above bullet point)
    
* Goal here is the choose a reinsurance program and its associated distribution $\Rightarrow$ More useful to look at the dist^n^ themselves

* Interested in the cost-benefit trade off, cost is the net cost of reinsurance and benefit is the protection against adverse deviation

**Space Needle View** on $\text{Premium} - \mathrm{E}[\text{Loss}]$

* Shows different percentiles

* Colored section is proportional to the probability that the result is in that range

* Easy to compare each quantile across programs

* Shows the shape of the distribution

**Cost Benefit Diagram**

* Cost of reinsurance (for each program) vs loss @ each percentile

* X-axis being the cost of reinsurance

* Y-axis is the loss amount (@ given percentile)

* We should expect the loss to decrease as we increase the cost of reinsurance

**Pre-Tax Net Income**

* Include expenses and investment income

* Look at value at each iterations of the sim (percentile)

* Get a perspective on overall profitability e.g. probability of negative earnings

* We can look at the probability of negative earnings

**CDF** on Combined Ratio

* **Caveat**: Can give distorted results when the net premium is reduced due to significant ceded premium

    * Expense ratio will be higher due to lower net premium (denominator)
    
    * Can make results look worst for program that have big cession
    
### Efficient Frontier Charts {#era-2-5-stability-5}

Construct the efficient frontier with a given **risk metric** (*x-axis*)and **return metric** (*y-axis*):

* Based on different reinsurance structure options

* For different percentile of the *return metrics*

```{remark}


* Plot increasing risk to the right so it looks more familiar

* Look for programs that are up and left along the efficient frontier with the lowest risk metric for a given return metric
```

*Return metrics*:

* e.g. Earnings

*Risk metrics*:

* Probability of making plan

* Probability of:

    * Surplus < 2 $\times RBC$
    
    * Surplus < BCAR score supporting a target rating
    
    * Expected loss in a 10 year period, $TVaR_{90\%}$, exceeds a threshold level or surplus
    
        (e.g. $TVaR_{90\%}$ should not exceed 20% of surplus)
    
    * x% drop in quarterly EPS

## Reinsurance as Capital {#era-2-5-sec-2}

Capital is held to pay for claims when the premium is not sufficient to do so

* Highly variable results will require more capital  

    $\Downarrow$  

    Reinsurance reduce volatility of results $\Rightarrow$ reduce capital required  

    $\Downarrow$  

    Reinsurance can be thought of as borrowed capital

We value the reinsurance by the impact it has in reducing Capital (or Cost of Capital)

$\therefore$ We compare the reduction in cost of capital to the cost of the reinsurance

***

Measure the amount of capital reduction that the insurer receives from the reinsurance program

* Compare the **cost of capital reduction** from reinsurance program

* i.e. Compare the marginal cost of reinsurance to the marginal capital to judge the value of reinsurance

```{definition, coc-reduct-met-1}
Cost of capital reduction: ***Metrics 1***

Net Benefit = |$\Delta$Cost of Capital| - |Net Cost of Reinsurance|

* Net benefit > 0 then accept

* **Net cost of reinsurance** = $\text{Reinsurance Premium} - \mathrm{E}[Recovery]$ on a PV basis

* Alt formula: Net benefit = Net Cost of Reinsurance - $\Delta$Cost of Capital

* Review other criteria when the dollar benefit is the same
```

```{definition, coc-reduct-met-2}
Cost of captial reduction: ***Metrics 2***

$ROE = \dfrac{\text{Net Cost of Reinsurance}}{\Delta \text{Capital}}$

* Compare return on equity

* We want $ROE$ **below** the *cost of capital* here and that lower is better since we are reducing capital

    * Think about it if you're going from the plan interested to gross, if the $ROE$ is lower you don't want to change so the current plan is better
    
    * Tink of this as investing negative capital, and $\therefore$ we want a **low ROE**
```

### Change in Capital {#era-2-5-change-in-cap}

2 different methods to determine the change in capital from the reinsurance structure

1. [Theoretical models](#theo-model-era-2-5):

    Use risk measures we discussed earlier (e.g. VaR, TVaR)

2. [Practical models](#prac-model-era-2-5):

    Use captial requirements from rating/regulatory agencies

#### Theoretical Models {#theo-model-era-2-5}

A risk metric is selected as a proxy to represent the economic capital required

* e.g. $VaR$, $TVaR$, multiples of $VaR$, $XTVaR$, etc

***Procedure:***

1. Calculate **Expected Earnings**

$$\text{Expected Earnings} = \text{Net Premiums} - \text{Expense} - \text{Expected Losses}$$

2. Calculate **Economic Captial**

$$\text{Economic Capital} = \text{Net Premium} - \text{Expenses} - \text{Risk Measures}$$

3. Measure the $\Delta$ in *Economic Capital* and *Expected Earnings* to determine the comparison metrics above (\@ref(def:coc-reduct-met-1) and \@ref(def:coc-reduct-met-2))

    * We measure the $\Delta$ against a base (*e.g. bare or current*)

    * Here $\text{Net Cost of Reinsurance} = \Delta \text{Expected Income}$
    
    * Remember that lower $ROE$ is better

#### Practical Models {#prac-model-era-2-5}

Use capital requirements from rating agencies (*e.g. BCAR, S&P, CAR, RBC, ICAR, etc*)

* Typically set target as a multiple of a given regulatory metric

    (e.g. 175% BCAR or 4 times RBC authorized control level)

Reinsurance reduces the capital required due to:

1. Lower *net premium* and *net reserves*

2. With a slight offset from increase *counterparty risk*

***Pros/Cons***

* **Pros**: Easier to implement (no need to model loss dist^n^ and correlation)

* **Cons**: Not as accurate because the measurement of risk is based on proxies and not the actual risk itself

    * e.g. stop loss only have small impact on premium but can have large impact on a risk (like the tail) that the method might not pick up

    * Alternatively, model a year out and predict the probability of falling below certain thresholds
    
        $\Rightarrow$ Capital could be set so that the probability is lower

    * But then we'll have to model the I/S and reinsurance structure and everything

### Theorectical Model Example: Marginal ROE

Compare the marginal cost of reinsurance to the marginal capital to judge the value of reinsurance

1) Pick a risk metric as proxy for capital required

2) Calculate **marginal capital** relative the current program

3) Calculate $\Delta$ NPV Net Benefit = $\Delta$ NPV Ceded Loss - $\Delta$ NPV Ceded Premium

4) Calculate $ROE = \dfrac{\Delta \text{NPV Net Benefit}}{\text{Marginal Capital}}$

5) Calculate *after-tax* $ROE$

* Compare the $ROE$ (We still want it lower?)

    * Bare in mind that a high ROE is meaningless if the amount of capital you can invest is small

#### XTVaR

Might be better to look at a multiple of XTVaR at a lower percentile

* XTVaR is the unfunded part of TVaR

$$XTVaR_{\alpha} = \mathrm{E}[Y \mid F(Y) > \alpha] - \mathrm{E}[Y]$$

* VaR is a single point and can be volatile at high percentiles

### Accumulation Risk {#era-2-5-acc-risk}

So far we implicitly assumed that the capital is held for only 1 year

* Capital calculated so far was static without regard to how long it takes to run it down as claims are paid

* Capital needs to be held until all claims are paid

#### "Life-time" Amount of Capital

$$\begin{align}
  \text{"Lifetime" amount of capital} \:\: = \:\: & \text{Capital for new business} \\
  &+ \text{Capital to support all unpaid claims from prior years} \\
\end{align}$$

$\therefore$ Set the capital requirements based on premium and reserves

* *Caveat*: Current reserves may be based on business that is different from this year's book (*e.g. size, mix of business, etc*)

* Use "*as-if*" reserves for capital calculation

```{definition, as-if-res-era-2-5, name = "As-if Reserves"}


* Calculate the reserves as if the company had been writing the same book the last several years

* Adjust for inflation

* Especialy important for long tailed lines where capital requirement for the accumulated outstanding reserve can be much large than the requirement for new business
```

Focus here is to determine the impacts on capital so we can assign a cost to each reinsurance program

* When comparing reinsurance program, the reserves would be calculated under each reinsurance program

* Capital calculated for both the new premium, and the loss reserves is a surrogate for the PV of the capital required for the current book over its lifetime

**2 Advantages** for the "as-if" reserves

1) Measure the impact of accumulated risk caused by correlated factors

    * Likely means "correlated risk factors" that can influence all those accident years (*e.g. inflation, change in law*)

2) Alternative reinsurance programs can be applied to the premium and as‐if reserves, providing a more valid measure of the accumulated risk and capital used over the full life of the AY

***

When aggregating AYs, we get temporal risk (risk based on time) that affect all AYs at the same time (*e.g. severity trend and auto correlation of severity trend*)

Including all AYs create a bigger spread of possible outcomes

### Capital Consumed {#era-2-5-cap-consum}

**Concept**: How much capital is needed to pay deficiencies

Plot/compare *PDF* and *CDF* of **Capital Consumed**:

\begin{equation}
  \text{Capital Consumed} = - PV[\text{Premium} + \text{Reserves} - \text{Losses} - \text{Expenses}]
  (\#eq:cap-con-equa)
\end{equation}

***Apply Reinsurance Example***

When modeling XoL contracts we need to model *severity trend*

* Severity trend impacts *all open claims*

* Payment pattern is important as claims that are open longer will have more severity trend applied

We can base the capital consumed on different risk measures (*e.g. VaR and TVaR*)

$$ROE = \dfrac{\text{Expected Profit}}{\text{Capital Consumed}}$$

* Do we want increase or decrease *ROE*? Probably increase

<span style="color:red">Comment from notes that author is not sure about</span>

## Reinsurance and Market Value {#era-2-5-sec-3}

Measure the impact on the **value** of the firm instead of the *impact on capital*

* Given 2 actions, the one that increases the value the most on a risk-adjusted basis would be preferred

* *Caveat*: We don't know how this can be done

* **Currently**: we measure value of the stability that reinsurance provides by measuring the reduction in capital

* **Next step**: Measure the value of reinsurance by measuring the $\Delta$ in the value of the company

***Highlights from recent studies***

* Insureds demand price discounts of 10-20 times the expected cost of an insurer default (EPD)

    * e.g. 0.5% default, expected cost = 100K if default
    
        $\Rightarrow$ EPD = 500
        
        $\Rightarrow$ Discount demand = 500 $\times$ 10 or 20 = 5-10K

* 1% decrease in capital $\Rightarrow$ 1% loss in pricing level

* 1% increase in $\sigma_{earnings}$ $\Rightarrow$ 0.33% decrease in pricing level

* Rating upgrades is worth 3% of business growth

* Rating downgrades can drop business by 5-20%

## Conclusion

Use cost-benefit analysis to compare reinsurance programs

* Select metrics to determine the *benefit of the reinsurance* and compare to *cost for each reinsurance programs*
    
Net cost of reinsurance = NPV of expected decrease in earnings from purchasing reinsurance = $\Delta$ PV[Expected loss - Premium - Reinstatement + Commission]

Combined ratio can be distorted due to expense ratio

**Stability** is the simplest measure of benefit

* But $\sigma$ can be misleading as they can be lowered by eliminating favorable results

Useful to look at the **differences of distributions** from the reinsurance options

**Efficient frontier** is useful

If we can measure the increase of value of the firm that would be great

* Increased earnings from reduced financing costs
    
* Higher premium from better claims paying ratings
    
* Can't do this right now so the substitute is to measure the reduction in capital requirements
    
Value of reinsurance can be measures vs:

* A cost of capital, or

* Capital (ROE)

## Past Exam Questions

**TIA Exercise**

* $\star$ TIA 1: Benefit of using a utility function

* $\star$ TIA 2: Reinsurance selection based on RORAC and EVA and reason for not doing allocation

* $\star$ TIA 3: Why might a non-marginal allocation lead to bad decision

* TIA 4: TVaR and VaR calc on a simple distribution

* TIA 5: Good properties for risk measure allocation

    * Does not ignore risk, if a risk is relevant to the BU, then is should be considered in the capital allocation for pricing
    
* TIA 6: Calculate different VaR measure for a givne $f(x)$

* $\star$ TIA 7: blurred VaR and why it is useful

* TIA 8: Factor model and it's deficiency

* TIA 9: UK stochastic model test

* $\star$ TIA 10: ALM application

* TIA 11: Why not duration match, impact of changing interest rate under different accounting

* $\star$ TIA 12: All the reinsurance metrics

* TIA 13: Efficient frontier

**Past Exam**

* 2011 #16: allocation method and use of transformed probabilities

* $\star \star$ 2011 #17: reinsurance options based on capital cost saving

* 2011 #19: Compare VaR and TVaR, calculate EPD

* $\star$ 2012 #13: Limitations of sample factor method and risk measures; how to reduce capital charge

* $\star$ 2012 #18: Pick the risk measures appropriate

* 2012 #20: Reason for purchasing reinsurance and what form to purchase

* $\star \star$ 2014 #22: risk adjusted capital and allocation with proportional and marginal allocation by first principle

* 2015 #24: Definition and limitation of VaR TVaR risk adjusted

* $\star$ 2015 #26: efficient frontier and reinsurance picking

* 2016 #22: ALM for soft and hard market

* $\star$ 2016 #24: Risk measures for differet LoBs

### Question Highlights

n/a