# ERA 4.1 & 4.2 Operational and Strategic Risk - D. Mango, G. Venter

***Op risk***

The risk of loss resulting from inadequate or failed internal process, people, and systems or from external events

[Types](#op-risk-type) of operational risk 

Underlying cause of insurer failure can be op risk even though if the surface cause is reserving or under pricing

Plan loss ratio example hows how optimistic loss ratio propagates forward

* 3 different reasons why the planned LR didn't work and only 1 of them is truly insurance risk

[Cycle management](#era-cycle-mgmt)

* [IP, u/w incentives, market overreaction, owner education](#era-4-CM)

6 [Additional persepctives](#add-pers-era-4-1)

***Strategic risk***

Various definition of strategic risk, no one clear definition, some overlaps with op risk

Various research to date

* Elements of strategic risk from Baird and Thomas

* Category of strategic risk from slywotzky and drzik

Scenario planning and the 10 [Steps](#scen-step)

* Look at the insurance example and the [advantages](#scen-adv) of scenario planning

Advance scenario planning

* Expend to several LoBs with dependencies

* Stochastic

* Agent based modeling (competitors, customers, regulators)

## ERA 4.1 Operational Risk Intro

Important cause of insurer insolvency $\Rightarrow$ Need to be aware and attempt to measure

```{definition, op-risk-basel, name = "Basel Op-Risk Definition"}


The risk of loss resulting from inadequate or failed internal process, people, and systems or from external events

* Include legal risk 

* Exclude strategic and reputation risk
```

**7 Types of Operational Risk Defined by Basel Committee**

1) Internal fraud

    * Acts that are intended to defraud, take property, or circumvent: regulations, law, or company policy
    
    * Includes at least one internal party

2) External fraud

    * Acts by a 3^rd^ party that are intended to defaud, take property, or circumvent the law

3) Employment practices and workplace safety

    * Acts *inconsistent* with: employment health, safety laws or agreements, which result in payment for: injury, claims for diversity of discrimination issues
    
    * e.g. repetitive stress, discrimination

4) Clients, products and business practices

    * Unintentional or neligent failure to meet a professional obligation to specific clients
    
    * Nature of design of a product
    
    * e.g. client privacy, bad faith

5) Damage to physical assets

    * Loss of damage to physical assets from natural disaster of other events
    
    * e.g. Physical damage to office, own auto fleets

6) Business disruption and system failures

    * Discruption of business of system failures
    
    * e.g. processing center downtime, system interruptions, flood

7) Execution, delivery and process management

    * Failed transaction processing or process management
    
    * Relations with trade counterparties and vendors
    
    * e.g. policy processing, claims payment errors

```{remark}


* Definition of op-risk has gained substantial visibility in ERM

    * For insurance though, the debate is always on going whether it is worth while to hold capital for op-risk
    
    * Different from banking, insurance op-risk are already baked into the other risk categories we measure and manage

* But still no consensus on how to define op-risk

* Could include reputational and strategic risk (just have a consistent risk taxonomy)

* Understanding of op risk is in its infancy especially with quantitative modeling

* Do not lose sight of op risk despite it is soft, difficult, poorly understood and lack historical track record
```

## Operational Risk to Insurers

Study show that insurer failure are mostly attributed to under **reserving** and **under pricing**

**Underlying cause** of insurer failure is actually *op-risk*

* e.g. Over accumulation of risk exposure (insufficient initial reserving or premature reserve release) given the asset base

* e.g. Overly optimistic plan loss ratios

Clear that op risk have heavily contributed to insurance impairments and should be **explicitly model**

* Currently capital charges for premium, reserve, and growth are *partially* **proxies** for operational risk

## Insurer Op Risk: Plan Loss Ratios

Mostly impact long tailed LoBs (e.g. 50% reported @ 5yrs, 90% @ 10yrs)

Optimistic loss ratio **propagates forward**

* Optimistic LR for older years lead to optimistic LR for th recent years

* Since the ELR is based on older years experience that might be too low, the planned LR is too low as well

As the older years losses develop higher than expected $\Rightarrow$ increase in reserves for all years, and can lead to:

* Rating downgrade

* Downgrade of claims paying ability

* Massive non-renewals

* No new business

* Eventual runoff

### Three reasons why the planned LR did not work

1) Model unable to forecast accurate LR

    * If the market and other carriers did fine, then the model was effective
    
        $\therefore$ *Op-risk*: Planning system did not deliver accurate LR, 
    
    * If everyone else failed to price properly, e.g. asbestos
    
        $\therefore$ A true insurance risk (unpredictable nature of long-tailed business)

2) Model was able to forecast accurate LR but was improperly used

    * *Op risk*: What checks were there to be sure the model was used correctly?

3) Model did accurately forecast the LR but indications were unpopular so ignored

    * *Op risk*: What governance should be there around management's decisions
    
## Insurer Op Risk: Cycle Management {#era-cycle-mgmt}

```{definition, era-4-1-cycle-mgmt, name = "Cycle Management"}
Prudent management of u/w capacity as market pricing fluctuates in the u/w cycle

* Simply maintaining market share during soft markets increases the likelihood of impairment
```

3 questions to ask:

1) Does the company have a **proactive cycle management** strategy? (if not, need?)

    * e.g. if we reduce rates (or increase exposure for the same premium) during soft market, it'll lead to increase reserve down the line

2) Does the company know **where in the cycle** the market stands

3) Are u/w-ers making **decisions that are consistent** with (1) and (2)

### System Performance Perspective

Assess an insurance company from a system performance perspective, it needs to be:

* **Stable** and **available** 

    * Downgrade impacts this

* **reliable** and **affordable**

    * Insolvent impacts this

### Performance Improvement via Cycle Management {#era-4-CM}

**Areas impacted** by implementing cycle management:

* *Planning*, *u/w*, *objective setting*, *incentive bonus*

Focus on the following to achieve meaningful process improvements:

* [Intellectual property](#era-4-CM-1)

* [Underwriter incentives](#era-4-CM-2)

* [Market overreaction](#era-4-CM-3)

* [Owner education](#era-4-CM-4)

#### Intellectual Property {#era-4-CM-1}

Majority of an insurer's **franchise value** are intangible

* They time consuming to build but easy to destroy

*IP examples*:

* Experts in various functions (*e.g. u/w, claims, finance, actuarial*)

* Proprietary database

* Forecasting systems

* Market relationship

* Reputation

Focus on **retaining these core assets** through cycle:

* Retain top talent, grow and develop their skills

* Maintain presence in core market channels

* Maintain consistent pattern of investment in systems, models and database

#### Underwriter Incentives {#era-4-CM-2}

Bonus should be based on u/w-er supporting the portfolio goals throughout the year

* Which may include writing less business

* U/w-er should know that it won't affect employment and bonus

#### Market Overreaction {#era-4-CM-3}

Industry tend to overreact (*taking prices too low and too high*)

Companies with most capital during price-improvement phase will reap windfall profits

* Which will more than offset many years of small u/w losses

#### Owner Education {#era-4-CM-4}

Educate owner/shareholders on the impact of cycle management on financial figures

Will be out of step with the market and does not appear healthy during soft markets:

* Premium volume $\downarrow$

    * Need to understand that growing exposure when the price is not adequate is not prudent

* Overhead expense ratio to premium $\uparrow$

    * Typically a metric for efficiency, but should be focus less
    
    * See this as capital investment in the assets of the firm and they will provide benefits to the firm in the future

## Miscellaneous {#add-pers-era-4-1}

Various different miscellaneous topics

* [Agency theory](#era-4-1-misc-1)

* [Op-risk management in banking and manufacturing](#era-4-1-misc-2)

* [Control Self-Assessment](#era-4-1-misc-3)

* [Key Risk Indicators](#era-4-1-misc-4)

* [Six Sigma](#era-4-1-misc-5)

* [Op-risk modeling](#era-4-1-misc-6)

### Agency Theory Perespective {#era-4-1-misc-1}

**Incentives** of managers and u/w-ers of the firm are *not always aligned* with shareholders

**Understand** the misalignment rather than try to fund for this op risk:

* Giving management equity stakes $\xrightarrow{\text{Caveat}}$ Manager too aggressive taking on more risk

* Equity is a large portion of management's net worth $\xrightarrow{\text{Caveat}}$ Too risk adverse

* Production incentives for u/w-ers $\xrightarrow{\text{Caveat}}$ Sloppy u/w-ing or mispricing

Key is to be aware of the problems and monitor results

* Have independent board members in this process

### Operational Risk Management in Banking and Manufacturing {#era-4-1-misc-2}

Op-risks that are common to all business:

* Pension funding

    * Both financial and HR component
    
    * **Quantifiable**: Models that incorporate financial risk and firm demographics

* IT failure:

    * Hardware or software failure, viruses and internet attacks
    
    * Need contingency planning
    
    * **Quantifiable**

* Other HR risks (loss of important staff, misdesign of comp program)

    * Loss of key staff (Could be due to misdesign of compensation program)
    
    * Employee liability, fraud, inadequate training, incompetence
    
    * **Identification** and **control** are more important

* Reputation risk

    * Damaged from product tampering, bad press, off-hours behavior of key employees
    
    * **Identification** and **control** are more important

* Lawsuits

    * Business practices can be misinterpreted or reinterpreted
    
    * Corporate culture makes a different
    
    * **Monitoring** is important, **funding** can be useful too

### Control Self-Assessment (CSA) {#era-4-1-misc-3}

```{definition, csa-era-4-2, name = "Control Self-Assessment"}
A process through which internal control effectiveness is examined and assessed

* Objective: Provide reasonable assurance that all business objectives will be met

* From Institute of Internal Auditors  
```

***Objectives of internal control***

* **Reliability** and **integrity** of information

* **Compliance** with policies, laws and regulations

* *Safeguarding* **assets**

* Economical and **efficient use of resources**

* **Accomplishment** of *objectives* and *goals* for operations or programs

### Key Risk Indications (KRIs) {#era-4-1-misc-4}

```{definition, era-4-2-kri, name = "KRIs"}
Broad category of measures that monitor the activities and status of the control environment of an operational risk category

* Measured frequently (e.g. daily)

* Have threshold that lead to escalation

* *Purpose*: Keep the risk management process dynamic and risk profiles current

* Forward looking, leading indicators of risk
```

***KRIs examples***

* *Production*: retention ratio, rate/exposure

* *Internal controls*: audit results and frequency

* *Staffing*: turnover rate, premium/employee, training budget

* *Claims*: frequency, severity

### Six Sigma {#era-4-1-misc-5}

Tolerances for output quality of $\pm 3 \sigma$ (born out of manufacturing)

Provides **framework for**:

* Process redesign

* Project management

* Customer feedback gathering

* Internal communication

* Design trade-offs

* Documentation

* Control plans

**Application**:

1. Existing process improvement

2. Predictive design

**Value proposition**:

* Useful in *high volume* processing

* Help *identify* and *eliminate* chronic process issues such as: 

    * Inefficiencies, errors, overlaps, gaps in communication and coordination

**Insurance example**:

* *U/w-ing*: exposure data verification, exposure data capture, classification

* *Claims*: coverage verification, ALAE, use of outside counsel, initial case reserve setting

* *Reinsurance*: treaty claim reporting, coverage verification, reinsurance recoverable, LoC, collateralization

### Operational Risk Modeling {#era-4-1-misc-6}

Operational risk manager needs to decide if risk should be *transferred* or *retained*

Based on insurance portfolio risk management, steps for operational risk portfolio management:

1) Identify **exposure base** for each *risk source* (premium, headcount, payroll)

2) Measure the **exposure level** for each BU and each op-risk source

3) Estimate the **loss potential** per exposure for each op-risk

4) Step 2 + 3 = loss freq and sev **distribution** for each BU

5) Estimate the *impact* of **mitigation**, **process improvements**, or **risk transfer**

    * This step requires significant expert opinion as there are no significant amount of loss data both before and after

Challenge is the lack of data available or they are recorded in an uncoordinated manner

* Worthwhile to begin to collect data

## ERA 4.2 Strategic Risk Intro

```{definition, era-4-2-strategy, name = "Strategy"}
Planning and the use of resources to achieve an organization's goals
```

```{definition, era-4-2-strategic-risk, name = "Strategic Risk"}
Intentional risk taking to achieve an organization's goals
```

**Scenario planning** is a key part of strategic risk management

* Think through the possible scenarios the firm could find itself in and to plan responses to those scenarios

* Advanced scenario planning incorporates several LoBs and includes dependencies among the LoBs

* Further step is **agent based** modeling where other parties reactions are also modeled

## History and Definition

```{definition, era-4-2-strategy-mw, name = "Strategy - Merriam-Webster"}


a. Science and art of employng the political, economic, pyschological and military forces of nation to afford the maximum support to adopted polices

b. The science and art of military command to meet the enemy under advantageous conditions

2. A careful plan or method

3. An adaptation for achieving evolutionary success, such as foraging strategies of insects
```

```{definition, era-4-2-strategy-mango, name = "Strategy - Mango"}


* Science and art of planning

* Using political, psychological, and organizational resources

* To achieve major organizational goals
```

```{remark}
The above aligns well with the GIRO (General Insurance Research Organization) definition
```

```{definition, era-4-2-strategy-giro, name = "Strategy - GIRO"}
A long term series of actions designed to take a company from its current state to its desired future state, and aim to provide a sustainable competitive advantage over other companies in the same market

Strategy in NOT:

* Business planning, strategy considers a wider breadth of issues such as the market, and where the company sits

* Tactics, as these are short term
```

```{definition, era-4-2-strategic-risk-2, name = "Strategic Risk"}


* Intentional risk taking

* Unintentional risk as by-products of strategy planning or execution
```

```{definition, era-4-2-strategic-risk-OCC, name = "Strategic Risk - OCC"}
Risk to earnings or capital arising from averse business decisions or improper implementation of those decisions. ... Its focus is on how plans, systems and implementation affect the franchise value
```

```{remark}


* OCC's definition focuses on unintentional risk

    * Which overlaps with op-risk by Basel:  
    *The risk of loss resulting from inadequate or failed internal processes, people and systems, or from external events. This definitions include legal risk, but excludes strategic and reputational risk*
    
* OCC includes system risk in strategic risk

    * Basel includes system risk in op-risk (which excludes strategic risk)
```

## Strategic Risk Management Research to Date {#era-4-2-strat-research}

* [Miller](#era-4-2-strat-research-1)

* [Baird and Thomas](#era-4-2-strat-research-2)

* [Slywotzky and Drzik](#era-4-2-strat-research-3)

* [Hertz and Thomas](#era-4-2-strat-research-4)

### Miller {#era-4-2-strat-research-1}

```{definition, era-4-2-miller-risk, name = "Risk - Miller"}
Unpredictability in corporate outcomes (effects)
```

```{definition, era-4-2-miller-uncertainty, name = "Uncertainty - Miller"}
Unpredictability of environmental and organizational variables that impact corporate performance (sources)
```
 
```{remark}


* Our definition of risk is closer to Miller's definition of uncertainty

* Our definition of strategic risk (unpredictable impacts of strategies), is what Miller refers to as strategic uncertainty
```

### Baird and Thomas {#era-4-2-strat-research-2}

```{definition, era-4-2-baird-old-risk, name = "Risk - Old 1921 paper"}
A condition in which the consequences of a decision and the probabilities associated with the consequences are know entities
```

```{remark}


* Baird and Thomas point out that the above lack clarity

* When making strategic decisions, the planners rarely know all the possible consequences or their probabilities

    * $\therefore$ the definition above does not capture strategic risk
    
    * Lack of knowing consequences or probabilities would be called *uncertainty* by theorists
```

```{definition, era-4-2-baird-strat-risk, name = "Strategic Risk - Baird and Thomas"}
Corporate strategic moves which cause returns to vary

* Which involve venturing into the unknown

* Which may result in corporate ruin

* Where outcomes and probabilities maybe only be partially known, and

* Where hard to define goals may not be met
```

***Elements of strategic risk***

* **Voluntariness** of exposure

    (Choose risk because potential benefits are larger than consequences)

* **Controllability** of consequences

    (Outcomes can be contained)

* Discounting in **time**

    (Ability to delay consequences)

* Discounting in **space**

    (Ability to shift risks to competitors)

* **Knowledge** of risky situation

* **Magnitude** of impact

* **Group/individual factors**

    (Is the leader of the group in favor of risk acceptance)

### Slywotzky and Drzik {#era-4-2-strat-research-3}

Table: (\#tab:era-4-2-drizk) Categories of Strategic Risk and Magnitude for Insurance Industry

| Risk | Examples | Magnitude | Comments |
| ---------- | --------------------- | --- | ----------------------- |
| Industry   | Capital Intensive; Overcapacity; Accommodation | Very High | |
| Technology | Shift; Patents; Obsolescence | Low | Possibly innovation in dist^n^ |
| Brand | Erosion; Collapse | Moderate | Reputation for fair claims handling |
| Competitor | Global Rivals; Unique Competitors | Moderate | Predatory pricing from competitors |
| Customer   | Priority Shift; Power; Concentration | Moderate | Bigger issue for large commercial insurance |
| Project | Failure of R&D; IT; Business Development; M&A | High | Insurers has long history of failed mergers; Low investment in IT |
| Stagnation | Flat or declining volume; Price declines | High | Highly correlated to the cycle; Companies will keep writing business to cover fixed expenses |

### Hertz and Thomas {#era-4-2-strat-research-4}

```{definition, era-4-2-risk-an-hertz, name = "Risk Analysis - Hertz and Thomas"}
An input for the strategy development process, aiding strategy formulation, evaluation, choice and implementation
```

```{remark}
Strategic risk analysis vs strategy formulation

* No distinction is drawn between strategic risk *analysis* and *strategy formulation*

* Both are viewed as part of a iterative, adaptive and flexible policy dialogue process
```

Definition above focus on how to make better strategy decisions and is **close to the *strategic error*** concept

## Scenario Planning {#era-4-2-scen-plan}

Effective strategic planning begins with scenario planning

***Key Characteristics*** on scenarios:

* **Limited # of scenarios**:

    Each tells a story of how elements may interact with each other under different conditions

* Test for **internal consistency** and **plausibility**

* Explore **joint impact** of several variables and change **multiple variables** at one time to capture new states after major shock

* Include **subjective interpretation** of factors that cannot be explicitly modeled

Attempts to capture the richness of range of possibilities $\Rightarrow$ Lead the makers to consider changes they might otherwise ignore

### Key Steps in Scenario Planning Process {#era-4-2-scen-plan-process}

1) Define **scope**:

    (*e.g. time frame, geography, market segment*)

2) Identify major **stakeholders**:

    (*e.g. employees, owners, regulators, customers, competitors, suppliers*)

3) Identify basic **trends** (and their influence on organization)

4) Identify key **uncertainties**:

    * Leverage points of impact

5) Construct **initial scenario** theme

6) Check for **consistency** and **plausibility**

    * Do outcomes fit together?

7) Develop **learning scenarios**:

    * Identify themes and naming scenarios

8) Identify **research needs**:

    * Areas that need additional research

9) Develop **quantitative models**:

    * Should formalize some interactions in a quantitative model?

10) Evolve toward **decision scenarios**:

    * *Iterative* process of reviewing scenarios with the goal of converging to test scenarios and generate new ideas

### Insurance Example

Scenarios will be **less detailed** than a typical strategy or plan document

* Goal is to generate a first-order approximation of the possible states

* Best place to try this is the **plan portfolio mix** (e.g. coming year WP and ELR by segments)

**Traditional unilateral planning approach**:  
Set planned premium and ELR based on current year base LR, cost trend, price change, target premium volume, LR

**Caveat**: Not thinking through other possibilities $\Rightarrow$ Not reacting properly while fixating on "making plan"

* Commitment to only one plan leads to organizational inertia, inflexibility that is unrealistic and potentially detrimental to the firm

* e.g. If price decrease, company might want to reduce premium volume instead of the inflexibility of making the planned premium volume

#### Basic Scenario Planning Example



Must **decide ahead of time**:

* Range of scenarios and relative likelihood

* Responses to those scenarios

Plans must have **enough detail** to give them operational weight

**Advantages**:

* **Thinks through responses** beforehand and can agree on best response ahead of time

    * With the rate change example, it allow u/w-ers to be flexible in their approach in case prices are not as expected

* Saves time during a crisis

* Operational **inertia is reduced**, flexibility is built into the system
    
## Advanced Scenario Planning & ERM

**Model Expansion**

* Expend into several LoBs

* Internal consistency requires coordination

* Need to model dependencies

* Responses will be politically charged, as limited u/w capacity must be allocated across the company

    * Better to do this during planning than in the heat of a market crisis

**Stochastic Scenario Planning**

Generate stochastically simulated scenarios that have responses based on a set of rules (This has been done with success in asset management)

1) Need to define **goals** that we want to achieve

    (*e.g. profit or premium level etc*)

2) Need to have **downside constraints**

    (*e.g. capital loss of x% with y% probability*)

3) Need to determine the essential **environmental variables** that define the state of the world
  
    (*e.g. size of market, price level, current market share, etc*)

4) Define **action rules** that respond to environmental variables

    (*e.g. hold price, increase u/w capacity according to price adequacy levels*)
    
    * Express as mathematical formulas that can be programmed into the simulation
    
## Agent-Based Modeling

Agents can be: *competitors*, *customers*, *regulators*

Program each agent to respond to the state of the market

* *e.g. Chase market share, focus on technical price, customer may reduce coverage if prices are high, etc*

Creates a complex system with emergent properties that describe the behavior of agents

* There emergent properties are often difficult to ascertain without running the simulations