# Formulas

Links to all key formulas

## Loss Development Using Credibility - E. Brosius

$\star$ Least Square (\@ref(prp:least-sq))

Theoretical Bayesian:

* Poisson - Binomial (\@ref(prp:poi-bin))

* Negative Binomial - Binomial (\@ref(prp:nb-bin))

$\star$ Best linear estimator formula (\@ref(prp:bayes-ble))

1. Estimate from data (prop. \@ref(prp:dev-form-1):
    
    * Alt form for $Z$ with equation \@ref(eq:brosius-alt-z)
    
2. $\star\star$ Use [$VHM$ and $EVPV$](#cred-dev) for $Z$

[Case load effect](#case-load)

## Credible Claims Reserve: The Benktander Method - T. Mack

GB method formula (\@ref(prp:GB-method))

Iterative form of BF and GB and it's extension: Theorem \@ref(thm:GB-iterate)

## Credible Claims Reserve: Benktander, Neuhaus and Mack - W. Hurlimann

$\star$ Credibility equation \@ref(eq:lr-claim-res-method) and the different $Z$ \@ref(tab:method-tbl-cred)

[Cape Code](#hur-remark)

[Credibility method MSE](#hurlimann-mse)

## Measuring the Variability of Chain Ladder Reserve Estimate - T. Mack

$\star$ 3 different **weight and variance** assumptions from table \@ref(tab:CL-var-weight)

$\star$ **Mean squared error** [calculation](#mack-mse-app)

* The big MSE formula \@ref(eq:mse-formula)

* How to get the $\alpha$'s we need for the MSE formula \@ref(eq:alpha-1) and \@ref(eq:alpha-2)

**Confidence Interval**

* Normal: equation \@ref(eq:normal-ci)

* $\star$ Log-normal: equation \@ref(eq:lognormal-ci)

    * Use log-normal when $s.e.(\hat{R}_i) > \dfrac{R_i}{2}$

$\star$ 4 **test of assumptions** to check

* Test 2. [Residuals](#mack-residuals)

    * Formula for residual \@ref(eq:residual-eq)

* $\star \star$ Test 3. [CY Test](#mack-cy-test)

    * How to get $z$ \@ref(eq:s-l-diagonal-mack)
    
    * Expected value \@ref(eq:exp-z-diagonal-mack) and variance \@ref(eq:var-z-diagonal-mack)
    
        * Or just memorize them up to 6 (Table \@ref(tab:cy-test-exp-var-table))

* $\star \star$ Test 4. [Adjacent LDF Correlation](#mack-adjacent-ldf)

    * $T$ for age $k$ \@ref(eq:t-k-mack) and $S$ \@ref(eq:sq-diff-rank-mack)

    * $T$ for the whole triangle \@ref(eq:total-t-mack)
  
    * CI to compare with resutls \@ref(eq:t-ci-mack)
    
        * This is test at a lower CI

## Testing the Assumptions of Age-to-Age Factors - G. Venter

$\star \star$ [Goodness of fit](#venter-goodness-fit) measure: 

* Adj SSE \@ref(eq:adj-sse-venter)

* AIC \@ref(eq:aic-venter)

* BIC \@ref(eq:bic-venter)

6 testable implications

2) $\star \star$ Is there a [better estimate](#venter-imp-2) for $q$ than $f \times c$

    * Number of parameters (Table \@ref(tab:venter-alt-pattern))
    
    * [Counting parameters](#venter-count-para)
    
    * $\star \star$ BF parameters (Table \@ref(tab:venter-var-weight-BF))
    
    * [Iteration process](#iteration-proc-venter)

5) $\star \star$ [No correlation among columns](#venter-imp-5)

    * Remember we are testing $f(d)$ so LDF - 1

    * Pearson correlation calculation \@ref(eq:venter-pearson-corr) and test statistics \@ref(eq:venter-pearson-corr-test-stat)
    
    * To test for all different pairs (not just adjacent pairs) \@ref(eq:corr-pair-total)

6) No particularly [high or low diagonals](#venter-imp-6)

    * Setting up regression with CY dummy variable \@ref(eq:venter-cy-regress)

## LDF Curve-Fitting and Stochastic Reserving: A Maximum Likelihood Approach - D. Clark

$\star$ Paper definition/standards:

* We use the **average age** of the period here (so minus 6 month)

**Reserve estimate**

* $\star \star$ Given $G(x)$ distribution 
    
    * **Loglogistic** \@ref(eq:clark-loglogistic), or
        
    * **Weibull** \@ref(eq:clark-weibull)
        
    * Might have to estimate parameters
    
* 2 Reserving method
    
    * $\star$ [LDF](#clark-ldf-method) Method

    * $\star$ [Cape Cod](#clark-cape-cod-method) Method
        
* Test for truncation by looking at age twice the triangle size
    
    * Different truncation method

[**Reserve process variance**](#clark-var-reserve)

* $\star \star$ Estimation of $\sigma^2$ \@ref(eq:clark-sigma-est)
    
    * Note the $n$ and $p$ for the 2 methods
        
    * We're looking at **incremental** losses

$\star \star$ Test $iid$ assumpation with [residual plots](#clark-res-review) by calculating standardized residual

[**Counting average accident date**](#avg-age-claim)

## A Model for Reserving Workers Compensation High Deductibles - J. Siewert

6 methods and their **pros** and **cons**:

1) [Loss Ratio Method](#siewert-lr-method)

    * Per occ \@ref(eq:siewert-lr-per-occ) and aggregate \@ref(eq:siewert-lr-agg) formula

2) [Implied Development](#siewert-implied-dev)

3) [Direct Development](#siewert-direct-dev)

    * See the 2 methods, \@ref(eq:siewert-direct-form-1) and \@ref(eq:siewert-direct-form-2), for calculating the $^{XS}LDF^L_t$
    
    * \@ref(eq:siewert-direct-form-2) is basically from method 5 proposition \@ref(prp:siewert-ldf-rel-3)
    
4) [Credibility Weight Method](#siewert-cred-weight-model)

    * Formula \@ref(eq:siewert-cred-wtd) weighting 1 and 3

5) [Development Method](#siewert-dev-method)

    * $\star \star$ Relativities \@ref(def:siewert-rel-form), severity LDF formulas, know them well to manipulate and know what formula requires what

        * Proposition \@ref(prp:siewert-ldf-rel-1) and  \@ref(prp:siewert-ldf-rel-2) are simlar one for limited one for XS
        
            * Might need to break out the $LDF_t$ into it's components
        
        * Proposition \@ref(prp:siewert-ldf-rel-3) combines the above
            * Note the 3 proposition above works with LDF if we sub out the ultimate relativities
        
        * Proposition \@ref(prp:inc-ldf-rel-1) and  \@ref(prp:inc-ldf-rel-2) are for *incremental* LDFs

6) [Distribution Method](#siewert-dist-model)

    * Use Weibull for $R_t^L$

Finally there's the method for accounting for [aggregate charge](#siewert-agg) with collective risk model or [table M](#siewert-agg-tbl-M)

## Claims Development by Layer - R. Sahasrabuddhe

$\star \star$ [Setup base triangle](#base-tri)

1. Set AY CY trend triangle

2. Unlimited mean loss *table* with \@ref(eq:unlimited-mean-sahas) **detrended**

3. LEV triangle @ $L$ and LEV for the last row @ $B$ with \@ref(eq:sahas-lim-exp)

4. Use \@ref(eq:base-layer-loss) to get base layer

$\star \star$ [Convert the base LDFs to any layer](#convert-ldf)
    
* Convert base layer LDFs \@ref(eq:layer-b-to-x)

* Convert to LDFs for XS Layers: \@ref(eq:sahas-ldf-xs)

Practical adjustments

* Formula when we don't have severity distribution for every  age \@ref(eq:sahas-only-diag) and how to estimate \@ref(eq:sahas-ratio)

## Using the ODP Bootstrap Model: A Practitioner's Guide - Shapland

***Model Parameters***:

* Mean \@ref(eq:odp-mean)

* Variance \@ref(eq:odp-var) and [dispersion factor](#odp-dispersion)

    * Need [residual](#odp-res): unscaled \@ref(eq:odp-pear-res), scaled \@ref(eq:odp-scaled-res), standardized \@ref(eq:odp-std-res)

$\star$ [***Simulation procedure***](#odp-boot-sim)

* Parameter variance \@ref(eq:odp-sim-loss)

* Process variance  \@ref(eq:proc-var-sim-shapland)

$\star$ ***Practical issues***:

1. $\star$ [Negative Incremental Values](#prac-issue-1)

    * During fitting: \@ref(eq:method-1-inc-neg-fit) and \@ref(eq:method-2-inc-neg-fit)
    
    * During simulation: \@ref(eq:gamma-adj-odp)

6. $\star$ [Heteroscedasticity](#prac-issue-6)

    * [Stratified sampling](#stratified-sample)
    
    * [Hetero adjustment to residuals](#hetero-adj-res)
    
    * [Non-constant scale parameter](#non-constant-scale-para)

## Obtaining Predictive Distributions for Reserves Which Incorporate Expert Opinions - R. Verrall

Model is defined with ([ODP or ODNB](#odp-nb-verrall)) and stochastic row parameters

* Moments for Mack: \@ref(eq:verrall-mack-mean) & \@ref(eq:verrall-mack-var)

* Moments for ODP: \@ref(eq:verall-odp)

* Moments fod OD NB: \@ref(eq:verall-odnb)

Bayesian BF calculation:

* Gamma moments \@ref(eq:verall-gamma-apriori)

    * Impact of $\beta_i$ on the Gamma variance

* Credibility formula \@ref(eq:bayesian-bf-verrall) and credibility weight \@ref(eq:verall-bf-cred-fact)

[Use](#stoch-col-bf) and [calculate](#verrall-gamma-calc) the stochastic column parameters

* Use the parameters with \@ref(eq:verall-odnb-col-para), see fig. \@ref(fig:verall-stoch-para)

* Calculate the parameters $\gamma_i$ pictorially, see fig. \@ref(fig:verall-gamma-calc)

## Stochastic Loss Reserving Using Bayesian MCMC Models - G. Meyer

**Interpretation** of all the [test](#meyers-test):

* KS-test: \@ref(eq:ks-expected-lower), \@ref(eq:ks-test-meyers-diff), and \@ref(eq:ks-test-meyers-criteria)

* $p-p$ plot (fig. \@ref(fig:meyers-p-p-plot))

    * Too light tailed: Shallow slope near corner and steep in the middle

    * Too heavy tailed: Steep slope near corner and shallow in the middle

    * Biased upwards: Bow down

* Freq vs Count plot (fig. \@ref(fig:meyers-freq-perc-plot))

***Bayesian Models*** (*Cumulative*):

* Lognormal \@ref(eq:meyers-loss-dist-lcl)

* $\beta = 0$ when it's done developing

* $\sigma$ constraint \@ref(eq:meyers-sigm-dist-lcl)

*Variations*

* [Leveled Chain-Ladder](#meyers-lcl) (LCL): Add variability to the row parameter with $\alpha$

    * Mean \@ref(eq:meyers-lcl-mean)

* [Correlated Chain-Ladder](#meyers-ccl) (CCL): Add AY correlation with $\rho$

    * Mean \@ref(eq:meyers-ccl-mean)

* [Changing Settlement Rate](#meyers-csr) (CSR): LCL with speed up claims closure with $\gamma$

    * Mean \@ref(eq:meyers-csr-mean)
    
    * $\gamma >0 $ for increase payout speed

**Bayesian Models** (*Incremental*):

* Distribution \@ref(eq:meyers-CIT-distribution)

    * Based on mixed lognormal distribution \@ref(eq:meyers-mix-log-norm-norm) (skewed log-normal \@ref(eq:meyers-skewed-normal) was not used)

* $\sigma$ constraint \@ref(eq:meyers-sigm-dist-cit) is different

* Additional constraint on $\beta$ so that it is decreasing

* Constraint on CY trend $\tau$

* Additional constraint on $\sigma$ so that it cannot increase drastically period to period

*Variation*

* [Correlated Incremental Trend](#meyers-cit) (CIT): LIT with added AY correlation $\rho$

    * Mean \@ref(eq:meyers-CIT-mean)
    
* [Leveled Incremental Trend](#meyers-lit) (LIT): Use skewed distribution and CY trend $\tau$

## A Framework for Assessing Risk Margins - K. Marshall et al.

$\star$ ***Correlation***

* The 3 main risk sources are independent of each other and therefore can be sum with square root rule \@ref(eq:marshall-source-2)

* **Independent** \@ref(eq:marshall-indep-corr):

    Assume independence across lines, weight by liabilities

* **Internal** \@ref(eq:marshall-int-sys-corr):

    Base on correlation matrix $\Sigma$, again weighted by liabilities

* **External** \@ref(eq:marshall-ext-sys-corr-1) & \@ref(eq:marshall-ext-sys-corr-2):

    Correlation between each valuation group and risk categories $\Rightarrow$ then roll up to the risk categories and assume they are independent of each other

***Risk Margin***: \@ref(eq:risk-margin-marshall)

* $\alpha$-tile \@ref(eq:risk-margin-alpha-marshall)

## Reinsurance Loss Reserving - Patrik

[Long tail reserving method](#patrik-long-est-methods):

1. Stanard Buhlmann

2. Credibility IBNR method ($Z = p_k \times CL$ and weighting **reserve** on $CL$ and $SB$)

## Estimating the Premium Asset on Retrospectively Rate Policies - M. Teng and M. Perkins

Retro formula: \@ref(eq:teng-retro-formula)

**Retro rating formula approach**

* $\star$ PDLD formulas \@ref(eq:pdld-1-form), \@ref(eq:premium-1-form), and \@ref(eq:pdld-n-subseq-form)

* Basic premium factor vs charge (charge is after tax)

**Empirical approach**

* Assume premium lags (typically 9 month)

* $\star \star$ Cumulative PDLD \@ref(eq:cpdld-ratio-perkin) and calculating it recursively \@ref(eq:cpdld-ratio-recurse)

* [Practical application](#application-teng)

    * First adjustment period might cover more than one policy period

Feldblum's adjustment to the empirical $CPDLD_1$ \@ref(eq:feldblum-adj-prem)

## P&C Insurance Company Valuation - R. Goldfarb

**Discount rate** 

* CAPM \@ref(eq:goldfarb-capm) and it's [components](#goldfarb-dis-rate)

$\star$ **Growth rate**

* Table \@ref(tab:goldfard-growth-rate) for each of the 3 method and it's [components](#goldfarb-growth)

[***DDM***](#goldfarb-ddm):

* DDM formula \@ref(eq:goldfarb-ddm-eq)

* Select $g$ by average of $ROE$ (usually $\rho$ is given)

    * If not then select $\rho$ too by average of $\rho = 1 - \dfrac{\mathrm{E}[Div_1]}{NI}$

[***FCFE***](#goldfarb-fcfe):

* FCFE formula \@ref(eq:goldfarb-fcfe-eq)

* Select $g$ by average of $ROE$ and reinvestment rate
    
[***AE***](#goldfarb-ae):

* AE formula \@ref(eq:goldfarb-ae-eq) and \@ref(eq:goldfarb-ae-eq-2)

[***Relative multiples***](#goldfarb-relative):

* Price:Earning \@ref(eq:goldfarb-PE)

* Price:Book \@ref(eq:goldfarb-PB)

# ERA 2.2 Risk Measures and Capital Allocation - G. Venter

Risk measures

* [Moment](#moment-base-era2-2) based

* [Tail](#tail-base-era2-2) based ($VaR$, $TVaR$, $XTVaR$, $EPD$), see table \@ref(tab:era2-2-tail-measure-tab)

* [Probability transform](#prop-trans-era2-2)

    * e.g. Esscher \@ref(eq:esscher-era-2-2)

* [Generalized moments](#gen-mo-era2-2)

Allocation of risk measures

* Definitions \@ref(def:cap-alloc-era-2-2-def)

* [Proportional](#proportional-era2-2)

* [Co-measures](#co-measures-era2-2), table \@ref(tab:era2-2-co-measure-tab) and \@ref(era2-2-co-measure-tab-2)

Allocation method properties:

* Marginal allocation \@ref(def:marginal-era2-2)

    * Scalable risk measures \@ref(def:scalable-era2-2)

* Suitable allocation \@ref(def:marginal-era2-2)

Marginal impact \@ref(eq:marginal-impact-era-2-2)