--- 
title: "CAS Exam 7 Study Notes"
author: "Cliff Lau"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: cliffordlau/Exam-7-2016-Notes
description: "CAS exam 7 study notes for 2017 Spring sitting."
---

# Overview {-}

CAS Exam notes for the [2017 Spring](http://www.casact.org/admissions/syllabus/Exam7.pdf) sitting.

Notes are broken down in to 3 main sections:

I. **Estimation of Policy Liabilities** (14 chapters)

* Learning Objective 1: **10-14%**
    
    1. Brosius
    
        *Loss Development Using Credibility*
    
    2. Mack (2000)
    
        *Credible Claims Reserve: The Benktander Method*
    
    3. Hürlimann
    
        *Credible Claims Reserve: Benktander, Neuhaus and Mack*

* Learning Objectives 2 & 3: **16-18%**
    
    4. Mack (1994)
    
        *Measuring the Variability of Chain Ladder Reserve Estimate*
    
    5. Venter Factors
    
        *Testing the Assumptions of Age-to-Age Factors*
    
    6. Clark
    
        *LDF Curve-Fitting and Stochastic Reserving: A Maximum Likelihood Approach*
    
* Learning Objective 4: **5-7%**
    
    7. Siewert
    
        *A Model for Reserving Workers Compensation High Deductibles - J. Siewert*
    
    8. Sahasrabuddhe
    
        *Claims Development by Layer - R. Sahasrabuddhe*
    
* Learning Objectives 5-10: **22-24%**
    
    9. Shapland (new 2017)
    
        *Using the ODP Bootstrap Model: A Practitioner's Guide*
        
    10. Verall
    
        *Obtaining Predictive Distributions for Reserves Which Incorporate Expert Opinions*
    
    11. Meyers (new 2016)
    
        *Stochastic Loss Reserving Using Bayesian MCMC Models*
    
    12. Marshall et al
    
        *A Framework for Assessing Risk Margins*
    
* Learning Objectives 11-13: **6-9%**
    
    13. Patrik
    
        *Reinsurance Loss Reserving*
    
* Learning Objective 14: **4-5%**
    
    14. Teng & Perkins
    
        *Estimating the Premium Asset on Retrospectively Rate Policies*

II. **Insurance Company Valuation** (1 chapter)

* Learning Objective 1-3: **8-12%**

    15. Goldfarb
    
        *P&C Insurance Company Valuation*

III. **Enterprise Risk Management** (11 chapter)

* Learning Objectives 1-6: **13-17%**

    16. ERA 1
    
        *Historical Context*
        
        *Overview of Enterprise Risk Management*
        
        *Enterprise Risk Modeling Overview*
    
    17. ERA 2.1
    
        *Corporate Decision Making Using an Enterprise Risk Model*
    
    18. ERA 2.2
    
        *Risk Measures and Capital Allocation*
    
    19. ERA 2.3
    
        *Regulatory and Rating Agency Capital Adequacy Models*
    
    20. ERA 2.4
    
        *Asset-Liability Management*
    
    21. ERA 2.5
    
        *Measuring Value in Reinsurance*
    
    22. ERA 3.1
    
        *Considerations on Implementing Internal Risk Model*
    
    23. ERA 3.2
    
        *Modeling Parameter Uncertainty*
    
    24. ERA 3.3
    
        *Modeling and Dependency: Correlations and Copulas*
    
* Learning Objectives 7 & 8: **4-6%**

    25. ERA 4.1 & 4.2
    
        *Operational Risk*
        
        *Strategic Risk*
    
    26. ERA 5.4
    
        *Approaches to Modeling the Underwriting Cycle*