---
title: "Exam 7 2016 Overall Summary"
author: "Cliff Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Section A

### A1 Least Square

Loss Development Using Credibility - Brosius

Least square methods

* Need to know how to calculate $b$

Theoretical Bayesian method and also estimating the Bayesian credibility with 2 methods for getting $Z$

* Can do $Z = \dfrac{b}{c}$ or the VHM EVPV formula
* Under certain relationships between $X$ and $Y$ supports different methods
* Some formulas to remember if we do the theoretical Bayes

Discussion on the caseload effect where the development and ultimate is not independent

### A2 Benktander

Credible Claims Reserve: The Benktander Method - T. Mack (2000)

Benktander Method

### A3 Credible Claims Reserve

Credible Claims Reserve: Benktander, Neuhaus and Mack - W. Hurlimann

Method that is based on the incremental loss ratio triangles

Weight between the analogous development and BF method

$R_i^c = Z_iR_i^{ind} + (1-Z_i)R_i^{coll}$

| $Z_i$ | Method |
| --- | --- | --- |
| 1     | Chainladder; Individual LR|
| 0     | BF; Collective LR|
| $p_i$ | Benktander |
| $p_i \times ELR$ | Neuhaus |
| $Z = \dfrac{p_i}{p_i + \sqrt{p_i}}$ | Optimal |

### A6 Variability in CL Method

Measuring the Variability of Chain Ladder Reserve Estimate - T. Mack (1994)

Focus on cummulative losses

Chain ladder **assumptions**:

1) $\operatorname{E}\left [c_{i,k+1} \mid c_{i,1} \cdots c_{i,k}\right ] = c_{i,k} \: f_k$
    
2) $\left \{c_{i,1} \cdots c_{i,I} \right \} \: {\perp\!\!\!\perp} \: \left \{c_{j,1} \cdots c_{j,I} \right \}$ for $i \neq\ j$
    
3) $\operatorname{Var}\left (c_{i,k+1} \mid c_{i,1} \cdots c_{i,k}\right ) = \alpha_k^2 \: c_{i,k}$

LDF weight and **variance** assumptions:

$\begin{align}
  \hat{f_k} = \frac{\sum_j \overbrace{\frac{c_{j,k+1}}{c_{j,k}}}^{LDF_j} \: w_{j,k}}{\sum_j w_{j,k}}
  \end{align}$

| Weight $w_{j,k}$ | Description | Variance | Residual |
| ---------------- | ----------- | -------- | -------- |
| 1                | Simple Average | $\alpha_k^2 \times \mathbf{c_{j,k}^2}$ | $\varepsilon = \dfrac{c_{j,k+1} - c_{j,k} \: \hat{f_k}}{\sqrt{\mathbf{c_{j,k}^2}}}$ |
| $c_{j,k}$        | Weighted Average | $\alpha_k^2 \times \mathbf{c_{j,k}}$ | $\varepsilon = \dfrac{c_{j,k+1} - c_{j,k} \: \hat{f_k}}{\sqrt{\mathbf{c_{j,k}}}}$ |
| $c_{j,k}^2$      | Least Square | $\alpha_k^2 \times \mathbf{1}$ | $\varepsilon = \dfrac{c_{j,k+1} - c_{j,k} \: \hat{f_k}}{\sqrt{\mathbf{1}}}$ |

**Mean squared error**

$\begin{align}
  MSE(\hat{c}_{i,I}) = \hat{c}_{i,I}^2 \Bigg \{ \sum_{k = I + 1 - i}^{I-1} \frac{\hat{\alpha}_k^2}{\hat{f_k}^2} \Bigg ( \frac{1}{\hat{c}_{i,k}} + \underbrace{\frac{1}{\sum_{j=1}^{I-k}c_{j,k}}}_{\text{Column x latest}}\Bigg ) \Bigg \}
\end{align}$

$\begin{align}
  \hat{\alpha}_k^2 = \frac{1}{I - k - 1} \sum_{j=1}^{I-k} c_{j,k} \Big ( \underbrace{\frac{c_{j,k+1}}{c_{j,k}}-\hat{f_k}}_{\text{AY LDFs - Selected}} \Big )^2
\end{align}$

For the last one $\alpha^2_{I-1}$:

* If the 3rd last one is lower, take that
* Else, you take the 2nd last times the ratio of the 2nd last to 3rd last

**Confidence Interval**

Normal: $\hat{R}_i \pm Z_\alpha \: s.e.(\hat{R}_i)$

LogNormal: $R_i \operatorname{exp}\left \{ -\dfrac{\sigma_i^2}{2} \pm \: Z_\alpha \sigma_i \right \}$

* $\sigma_i^2 = \operatorname{ln} \left [ 1 + \left ( \dfrac{s.e.(\hat{R}_i)}{\hat{R}_i} \right)^2 \right]$
* $\mu_i = \operatorname{ln}(\hat{R}_i) - \dfrac{\sigma_i^2}{2}$

**Assumptions test**

* Intercepts plot
* Residuals plot
* [CY Test](#a6-1)
* [Correlation on adjacent LDFs](#a6-2)

## Section B

### B1 Valuation Methods

B1 P&C Insurance Company Valuation - R. Goldfarb

The key methods are DDM, FCFE, and AE

* $V_0 = \dfrac{\mathrm{E}[Div_1]}{k - g}$
* $FCFE = NI + (Non \:Cash\:Charges) - \Delta Working \:Capital - \Delta Capital + \Delta Debt$
* $\begin{align} V_0 = BV_0 + \sum_{t=1} \frac{(ROE_t - k)BV_{t-1}}{(1+k)^t}\end{align}$

You can also look the P:Earning or P:Book multipes which have formulas that's based on the DDM and AE method

* Watch out for some nuance on forward and trailing P:Earning

Another important bit is to determine the growth rate, if it's not given in a questions then you have to calculate $g$ over a couple years and select

## Section C

## Formula Appendix

<a name="a6-1"></a> **Calendar Year Test**

Step 1) Rank the LDFs in each column

Step 2) Label them S and L and the median is discarded

Step 3) For each diagonal with at least 2 elements, $z = \operatorname{min}(\text{# of S}, \text{# of L})$

Step 4) Calculate $\operatorname{E}[z_n]$ and $\operatorname{Var}(z_n)$

* $\operatorname{E}[z_n] = \dfrac{n}{2} - c_n$

    * $n =$ # of elements in each diagonal **excluding** the throw away value
    
    * $c_n = {n - 1 \choose m}\frac{n}{2^n}$
    
    * $m = \operatorname{floor}\left[ \dfrac{n-1}{2} \right]$

* $\operatorname{Var}(z_n) = \dfrac{n(n-1)}{4} - c_n (n-1) + \operatorname{E}[Z_n] - \operatorname{E}[z_n]^2$

* $z \sim$ Normal

Step 5) See if $Z$ is in the CI based on the the above

* $Z = \sum_{diagonal} z$

* Since $Z \sim$ Normal, can sum the mean and variance by assuming independence

* Test 95% CI: $\operatorname{E}[Z] \pm 2 \times \sigma$

***

<a name="a6-2"></a> **Correlation of Adjacent LDFs**

Use a relatively low threshold of 50%

Step 1) Calculate Spearman's correlation for each pair of adjacent LDFs

* $S = \sum \limits_{\in rows} \Big \{ [Rank \: Col \: i \: LDF] - [Rank \: Col \: j \: LDF] \Big \}^2$

* Rank from low to high (i.e. lowest is 1)

* $T_k = 1 - \dfrac{S}{n(n^2-1)/6}$

    * $n =$ # of rows
    
    * For a 10 x 10 triangle, $k$ is at most 7 because there's only 9 LDFs so 8 pairs. And down to 7 because we don't use the pair with only 1 row
    
Step 2) Calculate $T$ for the whole triangle

* $T = \dfrac{\sum T_k (n_k - 1)}{\sum (n_k-1)} = \dfrac{\sum_k (I - k -1)T_k}{\sum_k I - k -1}$

    * $I =$ size of triangle
    
    * $k$ starts at 2
    
    * Formula gives more weight to $T_k$ with more data
    
    * Weight goes down to 1 for the last one, the bottom is just the sum of all the weights
    
Step 3) Compare $T$ with CI based on distribution

* $\operatorname{E}[T] = 0$

* $\operatorname{Var}[T] = \dfrac{1}{(I-2)(I-3)/2}$

* $\operatorname{E}[T] \pm Z \sqrt{\operatorname{Var}(T)}$

* Use $Z = 0.67$ for range of [25%, 75%]

* Do not reject the $H_0$ of uncorrelated LDFs if the $T$ is in the CI