---
title: "A3 Credible Claims Reserve: Benktander, Neuhaus and Mack"
author: "W. Hurlimann"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

## Credible Loss Ratio Claims Reserve

$p_i$ based on column loss ratios $m_k$

* $i$ are the AYs

* $k$ are development period

$\sum m_k$ = a priori ELR

* $m_k$ based on incremental column paid loss ratios

$p_i$ based on column loss ratios $m_k$

$R_i^c = Z_iR_i^{ind} + (1-Z_i)R_i^{coll}$

| $Z_i$ | Method |
| --- | --- | --- |
| 1     | Chainladder; Individual LR|
| 0     | BF; Collective LR|
| $p_i$ | Benktander |
| $p_i \times ELR$ | Neuhaus |
| $Z = \dfrac{p_i}{p_i - \sqrt{p_i}}$ | Optimal |

Notes:

* Neuhaus gives low credibility to lines with low loss ratios $\Rightarrow$ $\Delta$ exposure base will $\Delta$ result

* Optimal credibility is capped @ 0.5

* Benktander and Neuhaus reduce the MSE of the reserve estimate nearly to an optimal level outperforming individual and collective

**Individual Reserve Estimate**

$R_i^{ind} = q_i \dfrac{C_i}{p_i}$

Analogous to chainladder

**Collective Reserve Estimate**

$R_i^{Coll} = q_i(V_i \times ELR) = q_i(U_i^{BC})$

* BC = Burning Cost

Analogous to BF

### Optimal Credibility Weights

Walk through of how we got the optimal $Z^*$ formula

Minimize error between actual and estimate unpaid losses: $MSE(R_i^c) = \mathrm{E}[(R_i^c - R_i)^2]$

$Z^* = \dfrac{p_i}{q_i} \dfrac{Cov(C_i, R_i) + p_i q_i Var(U_i^{BC})}{Var(C_i) + p_i^2 Var(U_i^{BC})}$

* $p \uparrow \: \Rightarrow \: Z_i^* \uparrow$ because of $\dfrac{p}{q}$

* High $Cov(C_i, R_i)$ $\Rightarrow$ PtD and unpaid are correlated $\Rightarrow$ Credibility $\uparrow$

* Large $Var(U_i^{BC})$ $\Rightarrow$ Don't trust a priori

    * $Z \approx \dfrac{p}{q} \times \dfrac{pq}{p^2} = 1$
    
    * Give nearly full credibility to the CL when a priori has large variance

* Assumes $U_i^{BC} {\perp\!\!\!\perp} C_i$ and $R_i$
    
$Z_i^* = \dfrac{p_i}{p_i + t_i}$ After some assumptions about distribution of $\dfrac{c_i}{U_i}$

$Z_i^* = \dfrac{p_i}{p_i + \sqrt{p_i}}$ After some more assumptions

## Remark 6.1

Doing all the above with more "Traditional" method

* Get $p_i$ with $p_i^{CL}$, inverse of the CDF

* Get ELR with Cape Code

    * $\dfrac{\sum\limits_{i,k}S_{ik}}{\sum\limits_i V_i \times p_i^{CL}}$

* Benktander with $Z = p_i$

* Optimal Cape Code $Z = \dfrac{p}{p+\sqrt{p}}$

* BF use some other a-priori that varies by AY and $Z = 0$

    * I think this is right, manual said $Z=p$ but that seems wrong
    
