---
title: "C2 ERA 2.3 Regulatory and Rating Agency Capital Adequacy Models"
author: "Witcraft"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

## Introduction

Prior to 1990: Leverage Ratios

After 1990: Risk Based Capital Model (RBC)

Soon after RBC: Scenario Testing

More recently: Stochastic Scenario Testing

## Leverage Ratios

In early 1970s in US if companies fail 4 of 12 IRIS tests will get regulatory scrutiny

In US prior to the 1990s, 2 leverage ratio tests were used:

* $\dfrac{\text{Premium}}{\text{Surplus}} < 3.0$

* $\dfrac{\text{Reserves}}{\text{Surplus}} < a$ where $a$ is fixed

In EU Solvency I are equivalent to the higher of $\dfrac{\text{Premium}}{\text{Surplus}}$ and $\dfrac{\text{Incurred Claims}}{\text{Surplus}}$

And also net leverage $\dfrac{\text{Premium} + \text{Reserves}}{\text{Surplus}}$

Does not distinguish between LoBs

## Risk-Based Capital Models

Factor models, include other risks: asset, credit, premium, reserve

* Factors vary with the quality and type of asset or LoB

* Factors applied to accounting values

Used in UK, AUS, US, CA, JAP, AM Best and S&P

Models recognize accumulation risk (CATs) and multiple events instead of just occurrence amounts (most of them 1-in-100 or 1-in-250)

AM Best has much higher factors than the rest:

* Rating agency focus on long term viability vs regulatory focus on one year survival

* Correlation adjustment reduces the combined risk charge especially when the factors are of similar size

### Credit Risk

Largest component is reinsurance recoverable

Many models vary the factors with the credit quality of the reinsurers

AM Best increases credit charge for companies with high Reinsurance Recoverable / Surplus ratio

UK: premium ceded to one reinsurer can not > 20% of gross premium; Recoverable from an insurance group cannot > 100% of surplus

### Reserve Risk

Similar to premium factors, vary by LoB and applied to net reserves

Japan: reserve levels are low as payments are made quickly, factor is applied to net loss payment

### Accumulation Risk

Some models have started to use accumulation risk but many do not use it yet

Focus is on 1-in-100 or 1-in-250 events

## Scenario Testing

Some regulators require test of capital against scenarios

* Static scenarios in Canada (DCAT)

* Stochastic in UK and Australia with 99.5% of 1 year survival rate

* UK also have 3 years 98.5% and 5 year 97.5% survival

Stochastic modeling requires:

* Forecasting financials for 1-5 years
* Probability dist^n^ where they can be developed
* Dependencies among risks
* Reflection of Management Responses

## Evaluating Capital Structure Strategies

2 options to meet capital requirements:

**Purchase reinsurance**

Impact: 

* Premium $\downarrow$; Capital Requirement $\downarrow$

* Reserves $\downarrow$; Capital Requirement $\downarrow$

* Reinsurance Recoverable $\uparrow$; Capital Requirement $\uparrow$

    * Recoverables change is about 25% of the premium and loss reserve charge
    
Change in premium or reserve charge have a larger impact then to the recoverable charge due to the *covariance adjustment*

* Changes to small risk charges have a small impact on the total risk charge

Annual cost: Ceded Premium $\times$ Profit Margin

***

**Issue Surplus Notes**

Annual cost: (Surplus note yield - Bond yields) $\times$ Face Value of Surplus Note

However surplus note is a longer commitment as they can not be repaid for a certain time period

Reinsurance might be cheaper and the company can exit quickly