---
title: "C2 ERA 2.2 Risk Measures and Capital Allocation"
author: "G. Venter"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false    
    toc_depth: 4
---

## Introduction

VaR is too simplistic for insurance companies due to risk from reserves and u/w losses

Advantages attributed to **Economic Capital**

* **Unifying** measure for all risks in an organization
* More **meaningful** than RBC or Capital Adequacy Ratios (Prem/Surplus, Res/Surplus)
* Forces firm to **quantify** risks it faces and combine them into a probability dist^n^
* Provides a **framework for setting acceptable risk levels** for the company and its business units

(One of the risk measure discuss in the paper will be econ capital (?) Not all are econ capital)

Should consider multiple risk measures to see if the results are consistent

* Many other risk measures will also have the properties above
* Calling one of the risk measures economic capital is likely to confuse the process
    * (I guess econ capital is just a generic term?)
    
Current modeling approaches are not able to accurately estimate losses deep in the tail like 1-in-3000 (99.97%) event

* Bond ratings are discusses at this level but the ratings are not tied to the probabilities; Probabilities were simply observed

* Issue can be circumvented by focusing on events that can lead to impairment of the company, not just insolvency

Choosing probability level is an artificial exercise $\because$ There are no theoretical support to choose one level over another

* The company sometimes compare held capital to the loss dist^n^ stating that it's holding capital to cover a 1-in-x year event. But not the other way around like setting the capital based on it

Company is better off expressing the capital under various risk measures

## Risk Measures

3 major class of risk measures
* Moment-based (e.g. mean, variance)
* Tail-based (VaR, TVaR)
* Probability Transformation (WTVaR, Mean of Transformed dist^n^)

Risk measure can measure losses (like from insurance) but mostly mean negative profit (including premium charged) here

* $Y =$ Losses
* $\rho(Y) =$ Risk Measure

### Moment-Based Measures

$\operatorname{E}[Y^k]$ is the k^th^ moment of $Y$ which represent losses

* 1^st^ moment = Mean
* 2^nd^ central moment = Variance = $\operatorname{E}[(Y-\operatorname{E}[Y])^2]$
    * S.d. is preferred as it has the same units as the loss
* 3^rd^ moment = Skewness

$\operatorname{E}[Y e^{cY/\operatorname{E}[Y]}]$ captures all the moment using taylor expansion

* Does not exist unless there is a maximum possible loss

### Tail-Based Measures at $\alpha$ Percentile

| Risk Measure | Name                | Description                            |
| ------------ | ------------------- | -------------------------------------- |
| $VaR$        | Value at Risk       | $\alpha$^th^ Percentile                |
| $TVaR$       | Tail Value at Risk  | Avg loss above $\alpha$^th^ percentile |
| $XTVaR$      | XS Tail Value at Risk | $TVaR - Mean$                        |
| $EPD$        | Expected Policyholder Deficit | $(TVaR - VaR) \cdot (1 - \alpha)$ |
| Value of Default Put Option |      | Market cost of insuring for losses over $VaR_{\alpha}$|

* $XTVaR$ focuses on funding losses above the mean
* $EPD$ = unconditional expected value of defaulted losses if Capital = $VaR_{\alpha}$
    * If there was no risk premium required, this is the cost of insuring for losses over $VaR_{\alpha}$
* Value of default put is great than EPD, it includes an additional risk premium

### Probability Transforms

To recognize that large losses are worse for the firm in more than a linear way (e.g. losses twice as big is > twice as worst)

Change the loss distribution function by putting more weight (add probability) to the worst losses

* e.g. Esscher transform $f^*(y) = k \cdot e ^{y/c} \: f(y)$
    * Lower $c$ $\Rightarrow$ Higher losses from the transformed dist^n^
    * Can get non sensical results for $c$ that's too low
* $EPD$ on a transformed dist^n^ can give us the value of the default put

Comments

* Most asset pricing formulas like CAPM and Black-Scholes can be expressed as transformed means $\therefore$ transformed means are a promising risk measure for determining the market value of risk as it can also be the market value of the risk

* Complete market is where any risk can be sold, but we work in incomplete markets

* Theory of pricing in incomplete markets favors:

    * Minimum Martingale Transform (MMT)
    * Minimum Entropy Martingale Transform (MET)
    * These give reasonable approximations of reinsurance prices
    
* Mean under then Wang transform closely approximates market prices for bonds and CAT bonds

* $WTVaT$ is $TVaR$ on a transformed distribution

### Generalized Moments

Include more than just $\operatorname{E}[Y^k]$

$TVaR_{\alpha} = \operatorname{E} \left[ Y \cdot \left( Y > F^{ -1}(\alpha) \right) \mid Y > F^{ -1}(\alpha) \right]$

* $(Y > b) = \begin{cases} 1 & : Y > b\\ 0 & : \text{otherwise} \end{cases}$

* Average of $Y$ when $Y$ > than the $\alpha^{th}$ percentile: $F^{ -1}(\alpha)$

**Spectral Measures**

$\rho(Y) = \operatorname{E} \left[ Y \cdot \eta \left( F(Y) \right) \right]$

* $\eta \geq 0$

* Multiply the loss by a non-negative scalar $\eta(Y)$ when taking the expectations

**Blurred VaR**

$\eta(p) = \operatorname{exp} \left \{ - \theta (p-\alpha)^2 \right \}$

* Give more weight to losses near $\alpha^{th}$ percentile

* Still using the whole distribution

* $\theta controls how quickly the weight drops of as we get further from $\alpha$

***

Which risk measures to use

* $TVaR$ at a low percentile is fine as it captures all risks above this level; Set at level where we begin to loss capital

* Try to get close to market value of risk

    * $WTVaR$ with the MET is promising, or
    * Exponential moment $\operatorname{E}[Y e^{cY/\operatorname{E}[Y]}]$

## Required Capital

Capital a company should hold depends on *practical considerations*, not simply derived from a risk measure

* Risk measures should be used to measure the safety of the capital

Considerations that drive capital requirements:

* **Customers** reactions: Well capitalized insurer $\Leftarrow$ vs $\Rightarrow$ better price

    * $\downarrow$ rating $\Rightarrow$ $\downdownarrows$ of cumtomers since customers that want a higher level can quickly leave

    * $\uparrow$ rating $\Rightarrow$ $\upharpoonleft$ of growth since higher rating just provides an opportunity to compete with other insurers that already have the business

* **Keeping renewal business**: Have enough capital so that in adverse scenario there is still enough capital to service renewals that is x% of the business

***

Once capital level has been established, there are risk measures to compare it against

$TVaR$ is a better risk measure than $VaR$ for a given percentile since $VaR$ is just the smallest loss XS of a percentile, $TVaR$ is the average

## Capital Allocation

Allocate the company risk measure to each BU for the following purposes:

* Measure the amount of risk each BU contributes

* Set capacity and policy limits for each BU

* Calculate risk-adjusted profitability e.g. $\dfrac{\text{Profit}}{\text{Allocated Capital}} or EVA = Profit - Cost of Capital

***

Definition:

$Y$: Losses of a company

$X_j$: Losses for each BU, $\sum_j X_j = Y$

$\rho(Y)$: Risk measure of $Y$, $\mapsto$ a real number

$r(X_j)$: Allocation of risk measure to the individual BUs

* Usually different from $\rho(X_j)$, which is the risk measure applied to BU $j$

### Proportional Method

Allocate risk measure in proportion to the risk measure applied to each unit

$r(X_j) = \dfrac{\rho(X_j)}{\sum_i \rho(X_i)} \rho(Y)$

* $TVaR$: $r(X_j) = \operatorname{E}[X_j \mid F(Y) > \alpha]$; Condition on when the **firm** has losses XS the $\alpha^{th}$ percentile

* $VaR$: $r(X_j) = \operatorname{E}[X_j \mid F(Y) = \alpha]$; Condition on when the firm has losses at the $\alpha^{th}$ percentile

    * Difficult to calculate because it is estimating a single point in the dist^n^, results from sims can be quite variable

* Typical you're conditioning on the BU's $\alpha^{th}$ percentile

Not marginal if the condition is not on the firm's $\alpha$

* Marginal allocation means as unit grows, it is charged with the additional capital it requires

* Not marginal means the individuals don't sum to the total (?)

### Co-Measures

$r(X_j) = \operatorname{E}[h(X_j) \cdot L(Y) \mid g(Y)]$

Given that:

* $\rho(Y) = \operatorname{E}[h(Y) \cdot L(Y) \mid g(Y)]$
* $h(\cdot)$ is additive: $h(u+v) = h(u) + h(v)$

$\hookrightarrow$ $\rho(Y) = \sum_j r(X_j)$

* This is a marginal allocation that sums to the total risk measure

| Risk Measure | $h(Y)$ | $L(Y)$ | Condition | Co-Measure |
| ------------ | ------ | ------ | --------- | ---------- |
| $TVaR$ | $Y$ | $1$ | $F(Y) > \alpha$ | $\operatorname{E}[X_j \mid F(Y) > \alpha]$ |
| $VaR$ | $Y$ | $1$ | $F(Y) = \alpha$ | $\operatorname{E}[X_j \mid F(Y) = \alpha]$ |
| Standard Deviation | $Y - \operatorname{E}[Y]$ | $\dfrac{Y - \operatorname{E}[Y]}{\sigma_Y}$ | none | $\dfrac{\operatorname{Cov}(X_j,Y)}{\sigma_Y}$ |
| $XTVaR$ |   |   |   | $\operatorname{E}[X_j \mid Y > b] - \operatorname{E}[X_j]$

* Note for S.d.: $\rho(X_j) = \dfrac{\operatorname{Cov}(X_j,Y)}{\sigma_Y} = \operatorname{E} \left [ (X_j - \operatorname{E}[X_j]) \cdot \dfrac{Y - \operatorname{E}[Y]}{\sigma_Y} \right ]$ 

* For $XTVaR$:

    * $\rho(Y) = \operatorname{E}[Y - \operatorname{E}[Y ]\mid Y > b]$
    
    * Note the condition is on loss amount $Y$ not the percentile
    
    * Expected losses in unit $j$ when the company has a loss above $b$ less the expected losses in unit $j$
    
At low threshold, unit with higher mean have higher allocation

At higher threshold, unite with higher variance have higher allocation

### Having a Marginal Method

**Marginal Allocation**:  
Allocation is marginal if the change to the company's risk measure from a small change in a single BU is attributed to that business unit

* Consistent with concept that price should be proportional to marginal cost
* Leads to suitable allocation

***

**Scalable Risk Measures**:  
A small proportional change in the business change the risk measure by the same proportion

* Require that $\rho(aY) = a \cdot \rho(Y)$ $\Rightarrow$ Homogenous of degree 1

* Most measures in currency units have this property (e.g. S.D. TVaR) but not variance and probability of default

Scalability gives us that risk measure is both *marginal* and *additive*

Proportional change can be achieve from proportional reinsurance and normal growth

* Except for companies that write large policies compared to their volume; Transformed risk measure might still work

***

**Suitable Allocation**:  
Growing a unit that have above average profit/risk will increase the profit/risk for the company

Given $\dfrac{P_j}{r(X_j)} > \dfrac{P}{\rho(Y)}$

Show $\dfrac{P + \epsilon P_j}{\rho(Y + \epsilon X_j)} > \dfrac{P}{\rho(Y)}$

### Marginal Impact

A risk measure can have many co-measures but only 1 will be marginal

It is the one that is based on derivative of the firm risk measure w.r.t. growth in BU $j$

$r(X_j) = \lim \limits_{\epsilon \rightarrow 0} \dfrac{\rho(Y + \epsilon X_j) - \rho(Y)}{\epsilon} = \dfrac{\partial \rho(Y)}{\partial X_j}$

* Even under non-homogeneous growth, the risk measure is still decompositional (sum to the total) and is often close to marginal

$XTVaR$

* Scalable when done XS of a percentile $\alpha$

* $\operatorname{E}[X_j \mid F(Y) > \alpha] - \operatorname{E}[X_j]$

Variance

* $r(X_j) = \operatorname{Cov}(X_j,Y)$

* Not scalable, so not marginal

$VaR$

* $r(X_j) = \operatorname{E}[X_j \mid F(Y) = \alpha]$

Standard Deviation

* Spreading the s.d. $\propto$ mean is not marginal: $r(X_j) = \dfrac{\operatorname{E}[X_j]}{\operatorname{E}[Y]} \cdot \sigma_Y$

* This is marginal: $r(X_j) = \dfrac{\operatorname{Cov}(X_j,Y)}{\sigma_Y}$

Exponential Moment

* $r(X_j) = r_1(X_j) + \dfrac{\operatorname{E}[X_j]}{\operatorname{E}[Y]} \cdot c \cdot \operatorname{E} \left [ Y \cdot e^{cY/\operatorname{E}[Y]} \cdot \left \{ \dfrac{X_j}{\operatorname{E}[X_j]} - \dfrac{Y}{\operatorname{E}[Y]} \right \} \right ]$

    * Without the curly bracket it is just allocating $\propto$ the mean

    * Curly bracket (XS ratio factor) adjust for correlation, where BU that have large $X_j$ when Y is also large will have additional allocation; UBs that don't contribute to large losses will be negative in the curly bracket, receive reduced allocation
    
EPD

* $r(X_j) = (CoTVaR - CoVaR) \cdot (1-\alpha)$

* Only works when XS of a percentile

***

Table of Co-Measures

| Risk Measure | $h(Y)$ | $L(Y)$ | Condition | Co-Measure |
| ------------ | ------ | ------ | --------- | ---------- |
| $TVaR$ | $Y$ | $1$ | $F(Y) > \alpha$ | $\operatorname{E}[X_j \mid F(Y) > \alpha]$ |
| $VaR$ | $Y$ | $1$ | $F(Y) = \alpha$ | $\operatorname{E}[X_j \mid F(Y) = \alpha]$ |
| Standard Deviation | $Y - \operatorname{E}[Y]$ | $\dfrac{Y - \operatorname{E}[Y]}{\sigma_Y}$ | none | $\dfrac{\operatorname{Cov}(X_j,Y)}{\sigma_Y}$ |
| $EPD$ | $X - \operatorname{E}[X \mid F(Y) = \alpha]$ | $1-\alpha$ | $F(Y) > \alpha$ | $(CoTVaR - CoVaR) \cdot (1-\alpha)$ |

### Using Decomposition

If the allocated risk measure $r(X_j)$ is a decomposition of the company risk measure $\rho(Y)$ then we can use the measure to measure risk-adjusted profitability of a BU

$\dfrac{P_j}{r(X_j)}$

We also need $r(X_j) \propto$ [Market Value of Risk] for this to be an appropriate metric

* BU with higher ratio have more profit relative to the value of risk they are taking

However, we don't know how to determine the market value of risk $\Rightarrow$ Use several risk measures and hope that one is close and that the indicated strategic directions are consistent with each other

* Question on how to determine the market value of risk have not been settle yet, likely a risk measure on a transformed probability but we don't know yet

## Allocating the Cost of Capital

Compare profitability among the BU by allocate a cost of capital for each BU

2 possible definitions for cost of capital $C_j$

* Option pricing: Value of the right to call upon the capital of the firm

    * Difficult to value as the timing is not fixed in advanced
    
* Market value of a stop loss that attach at zero profits for the BU

    * Could use the expected value of the stop loss on transformed probabilities
    
    * MET is recommended
    
    * Practical estimate: Mean + 30% of s.d. would apply a consistent risk load to the BU
    
## Summary

Allocating capital, even using marginal decomposition is arbitrary and artificial

* Arbitrary because different risk measures give us different allocations and therefore different answers

* Artificial because the business unit has access to the entire capital of the firm, not just a portion of it

Using a value added approach, by allocating cost of capital is more economically realistic