---
title: "C4 ERA 4.1 & 4.2 Operational and Strategic Risk"
author: "D. Mango, G. Venter"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## 4.1 Operational Risk

Important cause of insurer insolvency $\Rightarrow$ Need to be aware and attempt to measure

**Definition from Basel**:  
The risk of loss resulting from inadequate or failed internal process, people, and systems or from external events

* Include legal risk but exclude strategic and reputation risk

**7 Types of Operational Risk Defined by Basel Committee**

1) Internal fraud
2) External fraud
3) Employment practices and workplace safety
4) Clients, products and business practices
5) Damage to physical assets
6) Business disruption and system failures
7) Execution, delivery and process management

***

Still no consensus on how to define op risk

Could include reputational and strategic risk, but as long as it is considered it is fine

Understanding of op risk is in its infancy especially with quantitative modeling

* Do not lose sight of op risk despite it is soft, difficult, poorly understood and lack historical track record

### Operational Risk to Insurers

Study show that insurer failure are mostly attributed to under reserving and under pricing

That is factually accurate, however in many case the underlying cause was actually operational risk

* e.g. Over accumulation of risk exposure (insufficient initial reserving or premature reserve release) and maybe just overly optimistic plan loss ratios

* Capital charges for premium, reserve, and growth are partially proxies for operational risk

Clear that op risk have heavily contributed to insurance impairments and should be explicitly model

### Insurer Op Risk: Plan Loss Ratios

Mostly impact long tailed LoBs (50% @ 5yrs, 90% @ 10yrs)

Optimistic loss ratio propagates forward

* Optimistic LR for older years lead to optimistic LR for th recent years

* Since the ELR is based on older years experience that might be too low, the planned LR is too low as well

As the older years losses develop higher than expected $\Rightarrow$ increase in reserves for all years, and can lead to:

* Rating downgrade
* Downgrade of claims paying ability
* Massive non-renewals
* No new business
* Eventual runoff

Three reasons why the planned LR did not work

1) Model unable to forecast accurate LR

    * If the market and other carriers did fine, then the model was effective
    
    * Planning system did not deliver accurate LR, therefore op risk
    
    * Unless everyone else failed to price properly, like asbestos

2) Model was able to forecast accurate LR but was improperly used

    * Op risk: What checks were there to be sure the model was used correctly?

3) Model did accurately forecast the LR but indications were unpopular so ignored

    * Op risk: What governance should be there around management's decisions
    
### Insurer Op Risk: Cycle Management

Cycle management:  
Prudent management of u/w capacity as market pricing fluctuates in the u/w cycle

* Simply maintaining market share during soft markets increases the likelihood of impairment

3 questions to ask:

1) Does the company have or need a proactive cycle management strategy
2) Does the company know where in the cycle the market stands
3) Are u/w-ers making decisions that are consistent with (1) and (2)

#### System Performance Perspective

From a system performance perspective, company needs to be:

* Stable, available, reliable, and affordable
* Downgrade impacts the first 2
* Insolvent impacts the last 2

#### Cycle Management

Areas impact by implementing cycle management:

* Planning, u/w, objective setting, incentive bonus

Focus on the following to achieve meaningful process improvements:

**Intellectual Property**

Intangible and are time consuming to build but easy to destroy

* Experts in u/w, claims, finance, actuarial
* P/h info database
* Forecasting systems
* Market relationship
* Reputation

Focus on retaining these core assets through cycle:

* Retain top talent, grow and develop their skills
* Maintain presence in core market channels
* Maintain consistent pattern of investment in IT and systems

***

**Underwriter Incentives**

Bonus should be based on u/w-er supporting the portfolio goals, which may include writing less business, and they should know that it won't affect employment and bonus

***

**Market Overreaction**

Companies tend to overreact, taking prices too low and too high

Companies with most capital during price-improvement phase will reap windfall profits, which will more than offset many years of small u/w losses

***

**Owner Education**

Owner/shareholders need to understand that some financial figures will be out of step with the market and does not appear healthy during soft markets:

* Premium volume $\downarrow$
* Overhead expense ratio to premium $\uparrow$

### Additional Perspectives {.tabset}

#### Agency Theory Perespective

Incentives of managers and u/w-ers of the firm are not always aligned with shareholders

Rather than try to fund for this op risk, better to understand it:

* Giving management equity stakes $\xrightarrow{\text{Caveat}}$ Manager too aggressive taking on more risk

* Equity is a large portion of management's net worth $\xrightarrow{\text{Caveat}}$ Too risk adverse

* Production incentives for u/w-ers $\xrightarrow{\text{Caveat}}$ Sloppy u/w-ing or mispricing

#### Operational Risk Management in Banking and Manufacturing

Risks that are common to all business

* Pension funding
* IT failure
* Other HR risks (loss of important staff, misdesign of comp program)
* Reputation risk
* Lawsuits

#### Control Self-Assessment (CSA)

**Definition** from Institute of Internal Auditors  
A process through which internal control effectiveness is examined and assessed. The objective is to provide reasonable assurance that all business objectives will be met

Objectives of internal control

* Reliability and integrity of information
* Compliance with policies, laws and regulations
* Safeguarding assets
* Economical and efficient use of resources
* Accomplishment of objectives and goals for operations or programs

#### Key Risk Indications (KRIs)

Broad category of measures that monitor the activities and status of the control environment of an operational risk category

* Measured frequently
* Have threshold that lead to escalation

Possible KRIs

* Production: retention ratio, rate/exposure
* Internal controls: audit results and frequency
* Staffing: turnover rate, premium/employee, training budget
* Claims: freq, sev

#### Six Sigma

Tolerances for quality if $\pm 3 \sigma$ based on manufacturing

Applied in process improvement or predictive design of processes

Useful in high volume processing

Help identify and eliminate: inefficiencies, errors, overlaps, gaps in communication and coordination

Insurance example:

* U/w-ing: exposure data verification, exposure data capture, classification

* Claims: coverage verification

* Reinsurance: treaty claim reporting, coverage verification, collateralization

#### Operational Risk Modeling

Operational risk manager needs to decide if risk should be transferred or retained

Steps for operational risk portfolio management:

1) Identify exposure base for each risk source (premium, headcount, payroll)

2) Measure the exposure level for each BU and risk source

3) Estimate the loss potential per exposure for each op risk

4) (2) + (3) = loss dist^n^ for each BU

5) Estimate the impact of mitigation, process improvements, or risk transfer

    * Requires significant expert opinion as there are no significant amount of loss data both before and after
    
## 4.2 Strategic Risk

### Intro Summary

Strategy: Planning and the use of resources to achieve an organization's goals

Strategic risk: Intentional risk taking to achieve an organization's goals

Scenario planning is a key part of strategic risk management

* Think through the possible scenarios the firm could find itself in and to plan responses to those scenarios

* Advanced scenario planning incorporates several LoBs and indcludes dependencies among the LoBs

* Further setp is agent based modeling where other parties reactions are also modeled

### History and Definition

**Strategy**

Definition from Mango:

* Science and art of planning
* Using political, pyschological, and organizational resources
* To achieve major organizational goals

Definition from GIRO:

* A strategy is a long term series of actions designed to take a company from its current state to its desired future state, and aim to provide a sustainable competitive advantage over other companies in the same market

Strategy in NOT (from GIRO):

* Business planning, strategy considers a wider breadth of issues such as the market, and where the company sits
* Tactics, as these are short term

***

**Strategic Risk**

Definition (unclear, but can be interpreted as):

* Intentional risk taking
* Unintentional risk as by-products of strategy planning or execution

Definition from OCC (more like op risk):

* Strategic risk is the risk to earnings or capital arising from averse business decisions or imporper implementation of those decisions. ... Its focus is on how plans, systems and implemenation affect the franchise value

* Very similar to operation risk and not strategic risk

### Research to Date {.tabset}

#### Miller

Strategic risk: unpredictability in corporate outcomes (effects)

Strategic uncertainty: unpredictability of environmental and organizational variables that impact corporate performance (sources)

* Our definition of risk is closer to Miller's definition of uncertainty

#### Baird and Thomas

Definition of risk too restrictive from an 1992 old paper:

* Risk: A condition in which the consequences of a decision and the probabilities associated with the consequences are know entitie

Baird and Thomas strategic risk definition (very broad):

* Corporate strategic moves which cause returns to vary, which involve venturing into the unknown, which may result in corporate ruin, where outcomes and probabilities maybe only be partially known and where hard to define goals may not be met

Elements of strategic risk:

* Voluntariness of exposure (Choose risk because potential benefits are larger than consequences)
* Controllability of consequences (outcomes can be contained)
* Discounting in time (ability to delay consequences)
* Discounting in space (ability to shift risks to competitors)
* Knowledge of risky situation
* Magnitude of impact
* Group/individual factors (is the leader of the group in favor of risk acceptance)

#### Slywotzky and Drzik

Categorize strategic risk

| Risk | Examples | Magnitude | Comments |
| --- | --- | --- | --- |
| Industry | Captial Intensive; Overcapacity; Commoditiztion | Very High | |
| Technology | Shift; Patents; Obsolescence | Low | Pos